README.md, defs.bzl
This adds `gmaven_artifact`, a convenience macro for users to directly specify the artifact's FQN. This saves users from grepping `gmaven.bzl` for target names, and mentally replace dots with underscores.
=> Add a macro to convert FQNs to generated target names

settings.xml
The license section on top of `settings.xml` was breaking the build with the following message:
> [ERROR] 1 problem was encountered while building the effective settings
> [FATAL] Non-parseable settings /home/fstephany/.cache/bazel/_bazel_fstephany/27c3a2bea20cb16a5910ae7660b43507/external/com_android_support_appcompat_v7_27_0_0/settings.xml: processing instruction can not have PITarget with reserveld xml name (position: START_DOCUMENT seen ...\n<?xml ... @14:7)  @ /home/fstephany/.cache/bazel/_bazel_fstephany/27c3a2bea20cb16a5910ae7660b43507/external/com_android_support_appcompat_v7_27_0_0/settings.xml, line 14, column 7
=> Fix License format in settings.xml

.gitignore, GMavenToBazel.java
Tested on my MacBook (2.4 GHz Intel Core i5), from 9 mins to about 3 mins.
On master branch: 
```
$ time ( java GMavenToBazel; ) 
( java GMavenToBazel; )  13.94s user 1.71s system 2% cpu 9:37.83 total
```
Checkout the requested branch:
```
$ time ( java GMavenToBazel; ) 
( java GMavenToBazel; )  15.96s user 1.55s system 10% cpu 2:43.81 total
```
=> Make 'gmaven.bzl' file generating more faster

examples/simple/WORKSPACE
The correct repository URL is https://repo1.maven.org/maven2.
=> Fix the build for the simple example

coursier.bzl
We shouldn't hardcode the path to `cat` on Windows. Derive it from `BAZEL_SH` instead.
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/36
=> Fix cat on Windows

.bazelci/presubmit.yml, coursier.bzl
And add the integration tests targets to macOS and Windows `build_targets` for Buildkite.
=> Unixify all paths and fix Windows builds

.bazelci/presubmit.yml
Turns out that 
```
foo:
bar:
-baz
```
is invalid yaml.
=> Fix invalid yaml

README.md, coursier.bzl
This tag can be used by rules to generate a pom file that includes the
coordinates of all of a target's dependencies
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/47
=> Add maven_coordinates tags to generated java_imports

.bazelci/examples.yml
The Windows failures will be fixed by https://github.com/bazelbuild/rules_jvm_external/pull/65
=> Fix target labels in examples CI configuration

coursier.bzl, third_party/bazel_json/lib/json_parser.bzl
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/53
When running any command on Windows via msys bash for the first time, msys bash prints:
```
Copying skeleton files.
--
These files are for the users to personalise their msys2 experience.
They will never be overwritten nor automatically updated.
'./.bashrc' -> '/home/SYSTEM/.bashrc'
'./.bash_logout' -> '/home/SYSTEM/.bash_logout'
'./.bash_profile' -> '/home/SYSTEM/.bash_profile'
'./.inputrc' -> '/home/SYSTEM/.inputrc'
'./.profile' -> '/home/SYSTEM/.profile'
<actual json>
```
and causes the JSON parser to choke on the first "C" character. Let's run `bash` once at rule initialization to do a simple `echo`, so further calls to `cat` don't result in this.
Successful build: …
=> Fix Windows builds on fresh instances, like CI

WORKSPACE, coursier.bzl, tests/unit/build_tests/BUILD
For example, the new error message for https://github.com/bazelbuild/rules_jvm_external/issues/70 looks like this:
```
The artifact for io.grpc:grpc-android:jar:1.16.1 was not downloaded. Perhaps its packaging type is
not one of: jar,aar,bundle,eclipse-plugin?
It is also possible that the packaging type of io.grpc:grpc-android:jar:1.16.1 is specified
incorrectly in the POM file of an artifact that depends on it. For example,
io.grpc:grpc-android:jar:1.16.1 may be an AAR, but the dependent's POM file specified its `<type>`
value to be a JAR.
The artifact(s) depending on io.grpc:grpc-android:jar:1.16.1 are:
com.google.firebase:firebase-firestore:18.1.0
and their POM files are located at:
/usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8484bc4fff18ee4a905b69a9ddb0e143/external/regr …
```
=> A better error message when Coursier fails to download artifacts.

defs.bzl
`REPOSITORY_NAME` is a read-only variable in Bazel Starlark in older versions. It's not an issue with new Bazel versions, but let's not use it anyway.
=> Stop using REPOSITORY_NAME as a variable name

.bazelci/examples.yml, .bazelci/presubmit.yml
This CL fixes the one breakage in the examples pipeline.
=> Fix missing yaml config and remove gmaven_rules app from CI

README.md, coursier.bzl
Convert standard *nix proxy environment variables into Java-style
property arguments, and add them to the generated coursier command.
=> Add proxy args to coursier command

.bazelci/examples.yml, examples/spring_boot/README.md, examples/spring_boot/WORKSPACE, examples/spring_boot/src/main/java/hello/Application.java, examples/spring_boot/src/main/java/hello/BUILD.bazel, examples/spring_boot/src/main/java/hello/HelloController.java, examples/spring_boot/src/test/java/hello/BUILD.bazel, examples/spring_boot/src/test/java/hello/HelloControllerIT.java, examples/spring_boot/src/test/java/hello/HelloControllerTest.java
This adds an example web application built with Spring Boot and rules_jvm_external, as requested by a user.
https://spring.io/guides/gs/spring-boot/
=> Add a example for Spring Boot

.bazelci/examples.yml, examples/scala_akka/.gitignore, examples/scala_akka/BUILD.bazel, examples/scala_akka/README.md, examples/scala_akka/WORKSPACE, examples/scala_akka/src/main/resources/application.conf, examples/scala_akka/src/main/scala/hello/Application.scala, examples/scala_akka/src/main/scala/hello/Configuration.scala, examples/scala_akka/src/main/scala/hello/Endpoint.scala, examples/scala_akka/src/main/scala/hello/Server.scala, examples/scala_akka/src/test/resources/application.conf, examples/scala_akka/src/test/scala/hello/ConfigurationSpec.scala, examples/scala_akka/src/test/scala/hello/EndpointSpec.scala
This PR adds and example of a fairly complex Scala application, and how to use the rules to successfully build / run / test it. In comparison to `bazel-deps`, we now need to define extra `deps` in order for `rules_scala` to pick them up. No big deal! @jin awesome job on this project!
=> (example): add scala akka http application.

coursier.bzl
This assumes that every artifact in the parsed Coursier output corresponds to a Bazel target, and will help us catch issues like the pom-only artifact.
=> Add an else clause to generate_imports to guide users to open an issue

tests/unit/build_tests/BUILD
https://buildkite.com/bazel/rules-jvm-external/builds/357#41f8a0b3-3c13-4c63-9a1e-c22a192c9c38
The regression testing still works because the failure from #111 comes from the repository rule, and not during the build.
=> Don't build test android aars on Windows

coursier.bzl
The first condition already checks if `target_label` is in `seen_imports`.
=> Remove redundant condition in generate_imports

coursier.bzl
This will give us a simpler error message than the one seen in https://github.com/bazelbuild/rules_jvm_external/issues/119#issuecomment-484278260
=> Don't print rdeps error message if there are no rdeps for the artifact

.bazelci/presubmit.yml
I have migrated ubuntu1804 to use OpenJDK 11, because that's the default JDK for that distribution.
During the migration I noticed that you have tests that fail with OpenJDK 11, so I recommend to
disable them until they're fixed.
For your reference, here's the log: https://buildkite.com/bazel/rules-jvm-external/builds/390#b676ef53-ae08-46ce-ae22-a2d4bc336479
=> Disable tests on ubuntu1804 that don't work with JDK11

README.md, coursier.bzl, defs.bzl
This PR adds support for Coursier's `--checksum` flag.
While it's not SHA pinning or verified with the actual SHA of the downloaded artifact, it's still better than *nothing* which is the case today.
Also, if one uses HTTPS Maven repositories, in-transit tampering should be reasonably secure.
=> Add support for Coursier checksum verification

examples/scala_akka/WORKSPACE
rules_scala also depends on protobuf and skylib but doesn't provide them in scala_repositories(), so we need to add them.
=> Fix Scala Akka example breakage by bumping rules_scala version

coursier.bzl, tests/integration/BUILD, tests/unit/build_tests/BUILD
Attempt to use versionless name in `jvm_import` and use versioned name in `alias`. 
Fix: #136
=> Use versionless jvm_import name

coursier.bzl
Here I faced an ERROR when using rules_jvm_external with $http_proxy set but is empty, and this pull request fix it.
```
ERROR: Analysis of target '//java:org_ray_ray_test_pom' failed; build aborted: no such package '@maven//': Traceback (most recent call last):
File "/private/var/tmp/_bazel_d-star/3d549a4d78f384e911df15e31f784ebc/external/rules_jvm_external/coursier.bzl", line 438
repository_ctx.execute(_generate_coursier_command(repos...))
File "/private/var/tmp/_bazel_d-star/3d549a4d78f384e911df15e31f784ebc/external/rules_jvm_external/coursier.bzl", line 438, in repository_ctx.execute
_generate_coursier_command(repository_ctx)
File "/private/var/tmp/_bazel_d-star/3d549a4d78f384e911df15e31f784ebc/external/rules_jvm_external/coursier.bzl", line 371, in _generate_coursier_command …
```
=> fix crashing when http_proxy is set but empty

README.md, coursier.bzl, defs.bzl, specs.bzl
Coursier allows users to pass in global package excludes (along-side artifact specific excludes) using the `--exclude` parameter.
This extends the `maven_install` rule to enable users to pass in exclude specs that apply globally.
```
maven_install(
....
excluded_artifacts = [
"com.google.guava:guava"
],
)
```
This is useful for porting over large code-bases that still mix pulling in explicit versions of packages and using `maven_install` for automatic package resolution.
Fixes #110
=> Allow passing in global package excludes

examples/android_instrumentation_test/WORKSPACE
```
$ bazel test --nobuild -k //... --incompatible_new_actions_api  --incompatible_no_transitive_loads  --incompatible_depset_is_not_iterable --incompatible_disable_deprecated_attr_params
INFO: Analyzed 6 targets (12 packages loaded, 870 targets configured).
INFO: Found 5 targets and 1 test target...
INFO: Elapsed time: 2.158s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
INFO: Build completed successfully, 0 total actions
```
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/148
fyi @laurentlb
=> Bump dependency on android/android-test to address Bazel incompatible changes

README.md, WORKSPACE, tests/integration/BUILD, tests/integration/GlobalArtifactExclusionsTest.java
This PR adds an JDK-11 compatible integration test for globally excluded artifacts using `maven_install.excluded_artifacts`.
=> Add tests for maven_install.excluded_artifacts

.bazelci/examples.yml
Passes with `$ bazel test //... --host_force_python=PY2 --incompatible_use_python_toolchains`
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/157
=> Fix incompatible change with python toolchains

README.md, WORKSPACE, coursier.bzl, defs.bzl, examples/simple/BUILD, examples/simple/WORKSPACE, private/compat_repository.bzl, tests/unit/build_tests/BUILD
This PR adds a new attribute, `generate_compat_repositories`, to `maven_install`. The default is `False`. The motivation for this change is https://github.com/bazelbuild/rules_jvm_external/issues/85. (Fixes #85)
With this, we can refer to `@maven//:junit_junit` as `@junit_junit//jar`, where the latter is the most commonly used naming convention that is popularized by rules like `maven_jar` and `java_import_external`. This enables project maintainers to incrementall migrate from `maven_jar` to `rules_jvm_external` without a single change in their BUILD files. It also allows cross-external repository sharing of artifacts.
If enabled, `maven_install` generates an additional `compat.bzl` file in the `@maven` (or your custom) external repository. This file exposes one symbol, …
=> Add generate_compat_repositories attribute to maven_install for top level repository aliases and cross-workspace dependencies

WORKSPACE, coursier.bzl, private/pin.sh, regression_testing_install.json, tests/unit/build_tests/BUILD
pin.sh had trouble serializing an artifact dependency identified by a version
range (ex: "[1.2.3,4.5)") because of unescaped end parentheses.  Work around
this by moving pin.sh's JSON template placeholder into a here-doc statement
and remove the corresponding quote-escape code from coursier.bzl.
Open q: Do we have to worry about command injection?
Resolves https://github.com/bazelbuild/rules_jvm_external/issues/178.
Testing Done:
- Generated a dependency set which named "io.kubernetes:client-java:4.0.0-beta1",
and the generated pin script no longer chokes.
=> Sidestep trouble with escaping json in pin.sh

coursier.bzl
This was caused by an incorrect use of `lstrip("unpinned_")`. 
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/182
=> Fix error in maven_install.json filename generation

README.md
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/181
=> Address pinned_maven_install aliasing when using multiple maven_install declarations

README.md, WORKSPACE, coursier.bzl, defs.bzl, policy_pinned_testing_install.json, tests/unit/build_tests/BUILD
This commit implements `maven_install`'s `version_conflict_policy` attribute
as described by @jin's comments ([1] and [2]).
`version_conflict_policy = "pinned"` translates to Coursier's
`-V group:artifact:version` for all requested artifacts.  The default of
"default" is a no-op.
[1]: https://github.com/bazelbuild/rules_jvm_external/issues/107#issuecomment-481460441
[2]: https://github.com/bazelbuild/rules_jvm_external/issues/107#issuecomment-481884679
Resolves #107.
Testing Done:
- added new test case to //tests/unit/build_tests
=> Implement version_conflict_policy to pin user's artifact versions

README.md, coursier.bzl, private/compat_repository.bzl, tests/unit/build_tests/BUILD
Make the generated compat repositories also generate the `@group_artifact//:group_artifact` / `@group_artifact` target label on top of `@group_artifact//jar` label to be interoperable with [`java_import_external`](https://github.com/bazelbuild/bazel/blob/master/tools/build_defs/repo/java.bzl#L25
). Some users refer to targets generated by `java_import_external` as `@group_artifact` instead of `@group_artifact//jar`. This was motivated by feedback in https://github.com/bazelbuild/rules_webtesting/pull/363#issuecomment-510121372.
Fixes https://github.com/bazelbuild/rules_jvm_external/pull/190
=> Add jar-less alias target for generate_compat_repositories mode

coursier.bzl, specs.bzl, tests/unit/specs_test.bzl
Passing the credentials as part of the repository URL is deprecated in coursier and has some unfortunate side-effects, such as the escaping of non-URL-safe usernames/password does not work correctly. (if you pass it in URL-escaped it does not work, if you pass it in plain it does not work either)
This PR does two things:
1. Use `--credentials` for `coursier` if the user passes in the credentials explicitly. If the user supplies an string for the repository URL it is passed-through as-is to coursier (which is also the current behavior). This means the having the basic-auth in the URL still works.
=> Fix passing credentials that are not URL-safe

.bazelci/presubmit.yml, WORKSPACE
This ensures that `rules_jvm_external` is backwards compatible for these versions.
=> Add Linux CI pipelines for 0.25.3 to 0.28.1 (latest) and update bazel-toolchains pin

private/pin.sh
When workspace A is calling `maven_install` of an external workspace B, the syntax of `maven_install_json = "//:maven_install.json"` will try to look for `maven_install.json` in workspace A. `maven_install_json = "@B//:maven_install.json"` will solve this problem.
Fix: #212
=> Prefix workspace name while referencing json

coursier.bzl
We didn't take private repository artifacts into account when implementing mirror_urls. Fixes https://github.com/bazelbuild/rules_jvm_external/issues/218
=> Fix private repository authentication regression in 2.6

WORKSPACE, examples/scala_akka/WORKSPACE
This is preparation for flipping [--incompatible_disallow_legacy_javainfo](https://github.com/bazelbuild/bazel/issues/5821).
=> Update rules_kotlin and rules_scala versions.

examples/android_kotlin_app/WORKSPACE
Makes tests compatible with [--incompatible_disallow_legacy_javainfo](https://github.com/bazelbuild/bazel/issues/5821).
=> Update rules_kotlin version in examples.

.bazelci/examples.yml
Kotlin rules now work on Windows.
Fixed in https://github.com/bazelbuild/rules_kotlin/pull/193
=> Reenable Kotlin example on Windows CI

coursier.bzl
Coursier recently added support for these packaging types to the default set to match SBT. We don't use the default set (`--no-default`), so we add them manually here.
https://github.com/coursier/coursier/pull/1207/files#diff-c1bcd89f837d1b694251360c98aa1d78
https://github.com/sbt/librarymanagement/blob/bb2c73e183fa52e2fb4b9ae7aca55799f3ff6624/ivy/src/main/scala/sbt/internal/librarymanagement/CustomPomParser.scala#L79
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/166
=> Support more packaging types to mirror Coursier's default set

private/pin.sh, scripts/generate_docs.sh, scripts/migrate_from_gmaven.sh, scripts/mirror_coursier.sh
Systems such as NixOS and BSD systems don't have bash in /bin
=> Use more portable Bash shebang

README.md, coursier.bzl, defs.bzl
Some of our resolves are starting to take longer than the default 600 second timeout for `repository_ctx.execute`.  
This PR adds a `resolve_timeout` attribute to `maven_install` so the timeout can be changed if needed.
=> add resolve_timeout attribute

README.md, private/versions.bzl
Resolves authentication issue in https://github.com/bazelbuild/rules_jvm_external/issues/80#issuecomment-531317963.
Fixes #80
=> Bump Coursier to 2.0.0-RC3-4

WORKSPACE, coursier.bzl, tests/unit/build_tests/BUILD
strict_visibility does not work for artifacts with classifiers.  e.g.
```
maven_install(
name = "strict_visibility_testing",
artifacts = [
maven.artifact(
group = "org.eclipse.jetty",
artifact = "jetty-http",
version = "9.4.20.v20190813",
classifier = "tests",
),
],
repositories = [
"https://repo1.maven.org/maven2",
],
strict_visibility = True,
)
```
will fail with
```
ERROR: rules_jvm_external/tests/unit/build_tests/BUILD:71:1: in genrule rule //tests/unit/build_tests:strict_version_classifier_0__deps: target '@strict_visibility_testing//:org_eclipse_jetty_jetty_http_tests' is not visible from target '//tests/unit/build_tests:strict_version_classifier_0__deps'. Check the visibility declaration of the former target if you think the dependency is legitimate
```
this PR adds classifier to …
=> Allow strict visibility to work for artifacts with classifiers

coursier.bzl, private/proxy.bzl, tests/unit/BUILD, tests/unit/proxy_test.bzl, tests/unit/specs_test.bzl
Addressing https://github.com/bazelbuild/rules_jvm_external/issues/261 so proxy Urls with user and password get parsed correctly and the `http.proxyUser` and `http.proxyPassword` are set accordingly.  
The method was broken out into a new file for easier testing.
=> Extract methods for parsing proxy Urls and add ability to parse proxy Urls with username and password

coursier.bzl
I have an entry of:
```
maven_install(
name = "zzz",
artifacts = [
"org.bouncycastle:bcpkix-jdk15on:1.61",
],
repositories = [
"https://xxx.yyy/repo",
),
)
```
And I have something in my `~/.config/coursier/credentials.properties` to give my creds. This confuses things currently because Coursier includes my name, but the repo doesn't know about it. I was previously getting an error because of `primary_artifact_path` being referenced before assigned.
=> Add missing case for primary_artifact_path

.bazelci/examples.yml
Probably an issue with line endings and `diff_test` -- disable the test for now.
=> Ignore failing protobuf-java test on Windows

README.md
`use_unsafe_shared_cache` was implemented before artifact pinning, and doesn't integrate directly with Bazel's repository cache.
=> Add a note to use_unsafe_shared_cache to recommend artifact pinning instead.

WORKSPACE, private/jvm_import.bzl, tests/integration/BUILD, tests/unit/manifest_contents/BUILD, tests/unit/manifest_contents/MANIFEST.MF.golden
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/283
With the repro in #283:
```
$ bazel build //:B_no_dep
INFO: Writing tracer profile to '/private/var/tmp/_bazel_jingwen/ac10292842231f27a13ff5ac097aa7a7/command.profile.gz'
INFO: Analyzed target //:B_no_dep (1 packages loaded, 14 targets configured).
INFO: Found 1 target...
ERROR: /Users/jingwen/code/rules_jvm_demo/rules_jvm/BUILD:16:1: Building libB_no_dep.jar (1 source file) failed (Exit 1)
B.java:6: error: [strict] Using type com.google.common.collect.Lists from an indirect dependency (TOOL_INFO: "@maven//:com_google_guava_guava"). See command below **
System.err.println(Lists.reverse(A.INTEGERS));
^
** Please add the following dependencies:
@maven//:com_google_guava_guava to //:B_no_dep
** You can use the following …
```
=> Extend jvm_import.bzl to stamp the jar's manifest with the Target-Label attribute for buildozer's add_dep feature

README.md
If upstream dependencies hardcodes the maven_jar repository name, this is a good solution / workaround without having to update the dependencies themselves.
=> Add documentation on repo_mapping for maven_jar migration purposes

.bazelci/presubmit.yml
We'll be adding netrc support in #306, which exists in later Bazel
versions. Let's stop supporting pre-1.0.0 versions.
The next rules_jvm_external will be a major version bump.
=> Drop support for Bazel beta versions

coursier.bzl, tests/unit/coursier_test.bzl
For every mirror url in a pinned json, try to extract netrc credentials. Then, write those credentials into a file that every generated http_file for the various maven artifacts will use.
Alternative way of implementing would be by allowing you to pass a pre-made netrc and that can be added in later if we should choose to do so, although it may be somewhat difficult to do so due to there being at least three different repositories in play making it difficult to use raw paths.
With this change, basic http auth will appear to be supported even though it technically isn't since we are translating basic http auth into netrc auth with all of netrc's shortcomings.
In the majority of cases I expect for this to be enough, but for complex auth schemes we may need something in addition.
Fixes …
=> Automatically generate a netrc file according to basic http auth in url

coursier.bzl
http_file will, by default, take in the $HOME/.netrc file to use for authentication.
This was broken by the earlier attempt to auto-generate netrc as a workaround for a lack of
inline http auth in http_file.
We now prepend the HOME netrc to the generated netrc file so that the HOME netrc serves as a
base which will get overlaid with the credentials in mirror_urls.
=> Pre-pend HOME netrc to generated netrc for inline http auth

examples/spring_boot/README.md
This documentation PR adds a link to a rule implementation that allows Bazel to build deployable jars for Spring Boot. It might be helpful to anyone following the Spring Boot example.
=> add link to Spring Boot deployable jar rule impl

.bazelci/presubmit.yml, README.md, coursier.bzl, tests/unit/coursier_test.bzl
`use_unsafe_shared_cache` is an optimization when not using artifact pinning. It bypasses Bazel's downloader, since it uses Coursier's internal downloader. The location of the cache can be specified with the environment variable `COURSIER_CACHE`. 
This PR adds support for reading `COURSIER_CACHE` when `use_unsafe_shared_cache = True`. If `use_unsafe_shared_cache = False`, `COURSIER_CACHE` is explicitly set to the output_base-internal location to ensure that Coursier doesn't write to the home directory. This fixes https://github.com/bazelbuild/rules_jvm_external/issues/301 (cc @arjantop)
This also adds vendoring support -- that is, using `use_unsafe_shared_cache` and `--repo_env=COURSIER_CACHE=$(pwd)/third_party` lets you download the jars directly into your source directory. Previously …
=> Support custom cache locations with use_unsafe_shared_cache and COURSIER_CACHE

WORKSPACE, coursier.bzl, defs.bzl, private/dependency_tree_parser.bzl, tests/unit/jetifier/BUILD, tests/unit/jetifier/jetify_all_test.sh, tests/unit/jetifier/jetify_include_list_test.sh
Allows user to include only certain artifacts for jetification.
This is not a breaking change as it keeps the default behavior intact, if user only sets `jetify = True` — all artifacts are jetified.
If user sets `jetify = True` **and** `jetify_include_list = [ … ]` then only included artifacts are jetified.
This allows to improve build times by avoiding jetification of artifacts that don't need it and avoid Jetifier bugs when it corrupts an artifact (haven't seen that in a while, but it was the case in past with some libraries).
This is a replacement for #348 as discussed in that PR.
=> Add jetify_include_list to jetify only specific artifacts

coursier.bzl
Can't reproduce the crashes anymore and multi-threaded fetch runs fine on this configuration:
Windows 10
Bazel 2.0
rules_jvm_external: 3.1
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/365
=> Using parallel threads for fetching on Windows

private/rules/jvm_import.bzl
After updating to version 3.1 (from 2.9) all external libraries in idea got a prefix `stamped_`
Its not a problem on its own.
But there is problem with idea plugin:
[It looks](https://github.com/bazelbuild/intellij/blob/c240371fbc3b3756b5faa2fa7f60130cb22327b2/scala/src/com/google/idea/blaze/scala/sync/BlazeScalaSyncPlugin.java#L78) for libraries which start with `scala-library` to configure scala sdk.
This fix will keep original jar names so they will be imported to idea with their original names
=> Preserver jar filename when stamping

.bazelci/presubmit.yml
Due to https://github.com/bazelbuild/rules_jvm_external/issues/375
=> Disable //tests/integration:UnsafeSharedCacheTest

.bazelci/presubmit.yml, .bazelrc, private/rules/jvm_import.bzl, settings/BUILD, settings/stamp_manifest.bzl, tests/unit/manifest_stamp/BUILD
There are a few reports of jar stamping being non-deterministic. This PR adds an ability to enable or disable the `Target-Label` stamping by passing the flag `--@rules_jvm_external//setting:stamp_manifest`.
=> Add a build setting `--//setting:stamp_manifest` to disable Target-Label stamping.

README.md, coursier.bzl
This enables e.g. increasing available memory settings for couriser (-Xmx).
=> Enable parsing COURSIER_OPTS env var to add parameters to coursier invocation

coursier.bzl, private/pin.sh, private/versions.bzl, tests/integration/BUILD
The formatted output is consistent with python2's `json.tool`.  No changes are required to how rules_jvm_external is added in the workspace nor how :pin is run.  I've tested on linux (centos) and OS X.
I didn't add jq for windows because I wasn't sure if pinning worked for windows at all, and I can't test it.  Should I add that as well?
=> use jq instead of python to format the pinned JSON (fixes #395)

README.md, coursier.bzl
Coursier download urls are hardcoded, hurdling firewalled environments without additional proxy support.
Use `COURSIER_URL` specify a custom download url.
Addresses #389
=> Allow for custom coursier download url via COURSIER_URL env var

README.md, coursier.bzl
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/383
```
$ RJE_VERBOSE=true bazel run @unpinned_maven//:pin
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8484bc4fff18ee4a905b69a9ddb0e143/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:68:9:
Current running Bazel is ahead of bazel-toolchains repo. Please update your pin to bazel-toolchains repo in your WORKSPACE file.
DEBUG: /usr/local/google/home/jingwen/.cache/bazel/_bazel_jingwen/8484bc4fff18ee4a905b69a9ddb0e143/external/bazel_toolchains/rules/rbe_repo/checked_in.bzl:125:9: buildkite_config not using checked in configs; Bazel version 3.1.0 was picked/selected but no checked in config was found in map {"0.20.0": ["8.0.0"], "0.21.0": ["8.0.0"], "0.22.0": ["8.0.0", "9.0.0"], "0.23.0": ["8.0.0", …
```
=> Add verbose mode to surface coursier stdout with RJE_VERBOSE

coursier.bzl, tests/unit/coursier_test.bzl
Every time I run `bazel run @unpinned_maven//:pin` it downloads every jar defined in the `maven_install` target because the @unpinned_maven repository is deleted every time it is "fetched".  Basically the Coursier cache used for fetching at `external/unpinned_maven/v1` is never re-used when you are updating the `maven_install.json` file.  
This PR changes the unpinned fetch so it uses Coursier's default cache locations or the COURSIER_CACHE env var for the cache.
By re-using the cache a `bazel run @unpinned_maven//:pin` update now takes around 60 seconds instead of 10-15 minutes when the cache is empty.
=> Use coursier's default cache directory when fetching jars to update the install.json file

coursier.bzl, tests/unit/coursier_test.bzl
Update how the default coursier cache path is calculated based on the existence of a $HOME/.coursier directory.  
Based on  https://github.com/coursier/coursier/blob/f48c1c6b01ac5b720e66e06cf93587b21d030e8c/modules/paths/src/main/java/coursier/paths/CoursierPaths.java#L60
From https://github.com/bazelbuild/rules_jvm_external/issues/417
Additional information: https://get-coursier.io/docs/cache.html#compatibility-with-former-versions
=> Fix coursier cache path logic for https://github.com/bazelbuild/rules_jvm_external/issues/417

coursier.bzl, private/pin.sh, private/versions.bzl
To do this, we download each version of jq that might be used and
ensure it's available. Decide at run time which version we'll use.
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/409
=> Allow `bazel run @maven//:pin` to run successfully

private/tools/java/rules/jvm/external/jar/DuplicateEntryStrategy.java, private/tools/java/rules/jvm/external/jar/MergeJars.java, private/tools/java/rules/jvm/external/zip/BUILD.bazel, tests/com/jvm/external/jar/BUILD, tests/com/jvm/external/jar/MergeJarsTest.java
Although the behaviour before was stable, it wasn't obvious, so this
change makes the behaviour of MergeJars explicit and configurable via
the command line.
This change also adds some (much needed) unit tests for MergeJars to
ensure that it behaves as we expect it should.
=> Make behaviour when merging duplicates configurable

private/rules/java_export.bzl, private/rules/maven_publish.bzl
Makes it easier to integrate with other Bazel tools that use the published artifacts.
---
b8499cd Add a provider to export the information being published
Make the provider available to external users.
<br/>
e8e110d Make maven_publish rule and "<name>.publish" target visible externally
For an external publishing tool, make the maven_publish rule (and the
"<name>.publish" target) visible to external targets.
This allows capturing the list of files (artifact, source, doc, pom) for
an external publishing tool to known about, reason about, and correctly
process these artifacts as needed.
<br/>
=> Add a provider to export the information being published

private/rules/java_export.bzl
Using "Tags" attribute on java_export() rule generates:
```
java_library(...)
got multiple values for parameter 'tags' via java_export rules
```
=> Handle tags in java_export rule

private/tools/java/rules/jvm/external/maven/MavenPublisher.java
JFrog Artifactory seems to accept only "Basic" casing.
Even though authorization scheme should be case-insensitive https://tools.ietf.org/html/rfc7617#section-2
=> Spell auth scheme as "Basic" for artifactory

coursier.bzl, private/pin.sh
Problem reported on #426
The build typically takes place in the user's workspace, so using
`$(location)` (or more correctly, `$(rootpath)`) gives an undesirable
"external/" leading segment. This would be useful if the binary being
run is in the users workspace, but we know our binary is in the same
workspace defining the BUILD file.
This change also uses the runfiles helper since I think that's required
to make this work on Windows, though I only tested on Mac.
=> Fix jq path in :pin runnable

examples/android_instrumentation_test/WORKSPACE
This platform is only valid on Linux machines, and breaks the build when
run from Windows or Mac.
The .bazelrc registers it as an execution platform when used with RBE.
=> Remove unconditional registration of :android_platform for execution.

coursier.bzl
handle the case where the username contains one or more '@' char (like an email address used as username).
=> Handle '@' in username

private/rules/maven_project_jar.bzl, private/tools/java/rules/jvm/external/jar/MergeJars.java, tests/com/jvm/external/jar/MergeJarsTest.java
I came across this difference between MergeJars and   https://github.com/bazelbuild/bazel/blob/master/src/java_tools/buildjar/java/com/google/devtools/build/buildjar/jarhelper/JarHelper.java#L124 when I was looking at jar tools.  Seems like it's better to use the same logic as JarHelper here.
=> Use JarHelper jar entry timestamp logic in MergeJars

private/rules/has_maven_deps.bzl, private/rules/maven_project_jar.bzl, private/tools/java/rules/jvm/external/jar/MergeJars.java, tests/com/jvm/external/jar/MergeJarsTest.java
Previously, we assumed that all the information required for a project
all code to be included was inside the main repository. This was put
in place largely to prevent code depending on `rules_proto` from
pulling in the classes from protobuf itself.
Issue #448 demonstrated that this assumption wasn't correct.
We now gather all the JavaInfos that should be included in the
artifact, as well as those of dependencies of the artifact (called
"dep_infos" in the MavenInfo provider) We then calculate the
difference of those sets to determine the input files to add to the
generated project jar.
However, this is not sufficient on its own in the case of
protocbuf. As such, we also scan for classes to exclude from the
project jar by examaning the contents of the "dep_infos" runtime jars.
Furthermore, …
=> Rework how maven project jars are calculated

README.md
Documentation was updated here: https://github.com/bazelbuild/rules_jvm_external/releases/tag/3.3
But it was not updated in this readme
=> Update documentation to use the latest names

WORKSPACE, tests/integration/BUILD, tests/integration/version-interval-deps.golden.dos, tests/integration/version-interval-deps.golden.unix
2.0.0-RC6-24 (and now 2.0.7 on RJE HEAD) brings bugfixes to artifacts that use version intervals in their deps, and add regression tests to fix #433.
See https://github.com/coursier/coursier/issues/1792 and https://github.com/bazelbuild/rules_jvm_external/issues/433
=> Add regression test for bug in artifacts that use version intervals for deps

private/rules/jvm_import.bzl, private/templates/BUILD, private/templates/manifest_target_label.tpl, private/tools/java/rules/jvm/external/jar/AddJarManifestEntry.java, private/tools/java/rules/jvm/external/jar/BUILD, tests/com/jvm/external/jar/AddJarManifestEntryTest.java, tests/com/jvm/external/jar/BUILD
Use custom java class to add Target-Label to the jar manifest so we maintain consistent modification time of the jar Manifest.
=> Use AddJarManifestEntry to add Target-Label to jars manifest

coursier.bzl, defs.bzl, private/dependency_tree_parser.bzl
Adds flag fetch_javadoc to maven_install rules. When used, javadoc for
all targets will be fetched by coursier and placed in a similarly
named filegroup.
=> Adds a flag to fetch javadoc targets (#494)

coursier.bzl
Allows to run :pin via multirun target regardless of strict visibility setting
Use-case is still to run it a a part of manual command, like 
```
load("@com_github_atlassian_bazel_tools//multirun:def.bzl", "command", "multirun")
command(
name = "pin-update",
arguments = ["$(rootpath //:jq)"],
command = "@unpinned_maven//:pin",
data = ["//:jq"], # may also try using jq from rules_jvm_external
)
multirun(
name = "maven-update",
commands = [
":pin-update",
":some-other-update-task", # for example update checked-in generated pom.xml that can trigger dependabot PRs/alerts
":maybe a task that reports something",
]
)
```
Making pin public may also allow using it at build or test time, bur probably not that useful unless it starts accepting arguments like target maven_install.json location
=> Make @unpinned_maven//:pin always visible

coursier.bzl
Option was added in https://github.com/bazelbuild/rules_jvm_external/pull/385
Not sure which bazel versions are strict about exposing env vars to repository rules, but
it seems that with bazel 3.3.1 COURSIER_OPTS isn't propagated by default.
One use-case is supporting proxy, for built-in repository rules it's possible for example to add following to .bazelrc
> startup --host_jvm_args=-Dhttps.proxyHost=... --host_jvm_args=-Dhttps.proxyPort=... --host_jvm_args=-Djavax.net.ssl.trustStore=... --host_jvm_args=-Djavax.net.ssl.trustStorePassword=...
Alternatively we could add TRUST_STORE and TRUST_STORE_PASSWORD env vars, but since COURSIER_OPTS is already here, let's stick with that one.
=> Declare COURSIER_OPTS to make it available

private/rules/jvm_import.bzl, private/tools/java/rules/jvm/external/jar/AddJarManifestEntry.java, private/tools/java/rules/jvm/external/jar/BUILD, tests/com/jvm/external/jar/AddJarManifestEntryTest.java, tests/com/jvm/external/jar/BUILD
Normally, bazel uses `ijar` to prepare a jar containing just
ABI-entries for classfiles. These are stable when non-API breaking
changes are made, and so allow bazel to compile code faster, and are
known as "compile jars"
Because of https://github.com/bazelbuild/bazel/issues/4549
`rules_jvm_external` doesn't use `ijar`, and instead uses the
downloaded jar as the "compile jar". Normally, this is fine, but Bazel
4.0.0 now sets `-Xlint:path` for javac invocations, and this means
that if there's a `Class-Path` manifest entry in a compile jar, the
jars within _that_ will be checked. This can lead to noisy builds:
https://github.com/bazelbuild/bazel/issues/12968
This change generates a "pseudo-compile jar" for `jvm_import`
targets. All it does is repack the input jar, excluding the …
=> Generate pseudo-compile jars for bazel java compilation

tests/integration/BUILD, tests/integration/version-interval-deps.golden.dos, tests/integration/version-interval-deps.golden.unix
This presorts the outputs of genquery before testing them, making them independent of graphless query or the bazel version under test.
Fixes: #529
=> Sort genquery outputs to be compatible with --incompatible_genquery_use_graphless_query

BUILD
This allows anyone who depends on `rules_jvm_external` and imports
"something" from these rules into their own rules to be able to
generate stardoc of their own functions.
I've filed https://github.com/bazelbuild/stardoc/issues/93 to track
this issue. Once it's fixed, we can close this.
=> Make documentation `bzl_library` publicly visible

docs/api.md, private/rules/java_export.bzl, private/rules/maven_project_jar.bzl, tests/integration/java_export/BUILD, tests/integration/java_export/check-deploy-env.sh
This allows `java_export` to be used to generate things such as
plugins for Apache Spark or jar files for use in JEE servers by
excluding provided dependencies from the generated jars. This is
analagous to maven's `provided` scope, and maps to the `deploy_env`
attribute of `java_binary`.
The difference between `java_export` and `java_binary`'s `deploy_env`
is that `java_export` allows anything that provides a `JavaInfo` as an
input to `deploy_env`. This is because the expected use-cases are for
things that are normally provided as regular imports from a maven
dependency, rather than a custom binary.
=> Add a `deploy_env` attribute to `java_export`

examples/android_instrumentation_test/BUILD
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/536
Same fix applied to android/testing-samples in https://github.com/android/testing-samples/pull/327
=> Set RBE machine type with KVM for instrumentation tests

private/proxy.bzl, tests/unit/proxy_test.bzl
Fix for HTTP_PROXY parsing when url doesn't have a scheme https://github.com/bazelbuild/rules_jvm_external/issues/541
=> Fix proxy parsing when HTTP_PROXY doesn't have a scheme (#541)

private/rules/maven_publish.bzl
Symlinks in DefaultInfo is not supported by remote build execution at
the moment (see https://github.com/bazelbuild/bazel/issues/13355).
Removing use of symlinks as a workaround for the time being since the
issue above is not trivial to fix.
---
The following command (assuming `bazel-rbe` is a wrapper to run bazel with remote build execution)...
```
bazel-rbe run //my/package:mytarget.publish --define "maven_repo=..." --remote_download_outputs=toplevel
```
...only works once this patch is applied. Before then, it would fail to find the artifact when being run.
There is currently a workaround consisting in running with `--remote_download_outputs=all` but it causes many unnecessary downloads.
=> Don't use symlinks in maven_publish DefaultInfo

private/rules/has_maven_deps.bzl, private/rules/maven_project_jar.bzl
In order to simplify `JavaInfo` provider, we're removing `transitive_exports` from it (and the native `TransitiveExportsProvider`). 
`rules_jvm_external` is the only downstream project, that this change breaks.
This PR works with both older and newer versions of Bazel.
Collecting exported labels in an aspect is a better option, because it work also over other Java-like targets (Kotlin, Android) which have JavaInfo provider. `transitive_exports` also creates problems when defining `JavaInfo()` and `java_common.compile` API (because Labels would need to be passed in).
Issue: https://github.com/bazelbuild/bazel/issues/13457
Design document: https://docs.google.com/document/d/10isTEK5W9iCPp4BIyGBrLY5iti3Waaam6EeGVSjq3r8/edit#bookmark=id.34gjanvu5611
=> Replace uses of JavaInfo.transitive_export with custom label collection.

private/rules/jvm_import.bzl
After the changes for https://github.com/bazelbuild/rules_jvm_external/pull/518 the `--@rules_jvm_external//settings:stamp_manifest` flag only kept the stamp out of the outjar and not the compile jar.  This update means the flag will always keep the jar from getting stamped if the flag is set.
Follow up question:  Do we want to keep this flag anymore?
=> Fix stamp_enabled flag so the jar isn't modified if the flag is set

README.md, coursier.bzl
---
d49ec1f feat(pin): allow only repinning the rules_jvm_external lockfile
Now that rules_rust and rules_jvm_external both support the same
repinning method, make it possible to choose to repin a single lockfile
or all lockfiles.
Refs: https://github.com/bazelbuild/rules_rust/pull/682
<br/>
=> feat(pin): allow only repinning the rules_jvm_external lockfile

private/pin.sh
@// refers to the root workspace of the bazel invocation, regardless of
which repository it's referred to in.
This avoids needing to run `bazel info` from inside the `bazel run`.
=> Use @// instead of @${workspace_name}//

WORKSPACE
Remove `build_tools_version` and `api_level` to let `android_sdk_repository` automatically select the latest installed version.
One of the fixes for https://github.com/bazelbuild/bazel/issues/13409#issuecomment-845265150
=> Remove build_tools_version and api_level

private/rules/has_maven_deps.bzl, tests/unit/exports/BUILD, tests/unit/exports/exports_test.bzl
https://github.com/bazelbuild/rules_jvm_external/pull/557 replaced using
`JavaInfo.transitive_exports` by instead using
`HasMavenDeps.transitive_exports` but it changed how this was computed.
The JavaInfo traversal code:
https://github.com/bazelbuild/bazel/blob/5a647bb234ba9817f51fdb2b4b5973a0602f51a4/src/main/java/com/google/devtools/build/lib/rules/java/JavaCommon.java#L341-L357
only follows the `exports` attribute, and merges together each of the
transitive exports it finds that way.
The replacement starlark code was traversing each of `deps`, `exports`,
and `runtime_deps`, looking for anything which may have been exported
_to_ those targets, which exports significantly more targets.
This adds a unit test to prevent future regressions.
=> Don't export via deps, only via exports

.bazelci/presubmit.yml, README.md, WORKSPACE, coursier.bzl, defs.bzl, tests/bazel_run_tests.sh
Print a warning when an artifact appears in the list more than once. For example for the following maven_install
```
maven_install(
name = "maven",
artifacts = [
"com.fasterxml.jackson.core:jackson-annotations:2.10.1",
"com.fasterxml.jackson.core:jackson-annotations:2.12.1",
"com.fasterxml.jackson.core:jackson-annotations:2.10.1",
"com.fasterxml.jackson.core:jackson-annotations:2.11.2",
"com.github.jnr:jffi:1.3.3",
maven.artifact(
group = "com.github.jnr",
artifact = "jffi",
version = "1.3.3",
classifier = "native",
),
maven.artifact(
group = "com.github.jnr",
artifact = "jffi",
version = "1.3.2",
classifier = "native",
),
],
repositories = [
"https://repo.maven.apache.org/maven2/",
],
)
```
print the following
```
>  bazel run @maven//:pin         
DEBUG: …
```
=> Print a warning when there is a duplicate artifact in the artifact list

.bazelci/examples.yml
Android Emulator on RBE basically works accidentally on their platform and it could stop working any time.
I'm removing the test because it is failing (see https://buildkite.com/bazel/rules-jvm-external-examples/builds/1960#4cef1180-9796-4dff-ae98-222391d9bc5a)
=> Remove android_instrumentation_test on RBE

.bazelci/presubmit.yml
https://github.com/bazelbuild/rules_jvm_external/issues/586
=> Disable https://github.com/bazelbuild/rules_jvm_external/issues/586 on Windows CI

private/proxy.bzl, tests/unit/proxy_test.bzl
Should fix https://github.com/bazelbuild/rules_jvm_external/issues/581
=> Quote http.nonProxyHosts argument to java so the pipes separating the hosts to not get interpreted by the shell

coursier.bzl, private/java_utilities.bzl, tests/unit/BUILD, tests/unit/java_utilities_test.bzl
Should fix https://github.com/bazelbuild/rules_jvm_external/issues/549 if they are using Java 9 or higher
=> Use argsfile for java if we are using java 9 or higher to avoid command line length limits

README.md
The README.md appears documented the `rules_jvm_external` usage incorrectly.
`rules_jvm_external_setup` doesn't have the parameter of `repositories`, instead `rules_jvm_external_deps` has it.
Reference to `rules_jvm_external_deps`
https://github.com/bazelbuild/rules_jvm_external/blob/fa73b1a8e4846cee88240d0019b8f80d39feb1c3/repositories.bzl#L8
=> Fix usage code snippet in README

examples/android_local_test/WORKSPACE
The `Robolectric` 4.4 has been released, https://github.com/robolectric/robolectric-bazel/releases/tag/4.4. This PR bumps example's `Robolectric` version to 4.4.
=> Bump Robolectric to 4.4

coursier.bzl, private/pin.sh
Redid pin.sh as this fails on linux when the json file for maven dependencies becomes very large. Switches to using a intermediary file.
=> Fix jq not formatting large (> 4 MB) in linux

WORKSPACE, private/dependency_tree_parser.bzl, tests/unit/aar_import/BUILD, tests/unit/aar_import/aar_import_test.bzl
Appending the srcjar when available to the `aar_import`.
=> Append srcjar to aar_import

examples/scala_akka/WORKSPACE
Fixes breakages on downstream builds with newer version of Bazel:
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2241#a891e788-ab68-4a71-a585-e5b240c2ad1e
=> Upgrading version of rules_scala.

private/rules/java_export.bzl, private/rules/maven_publish.bzl, private/tools/java/rules/jvm/external/maven/MavenPublisher.java, tests/integration/java_export/BUILD
Occasionally generating javadoc jars is more complicated than
compiling the raw source code (eg. when documenting code that uses
Lombok) Rather than make people jump hoops to generate the javadoc jar
(which may not actually be used) add a new tag we check for:
`no-javadocs`
=> Make generating javadoc jars optional

private/artifact_utilities.bzl
https://github.com/bazelbuild/rules_jvm_external/commit/d98ea59caa97e26a21e773a773c95dd5cf880126#r60658332
We encounter this bug when using the newest code.
```
ERROR: An error occurred during the fetch of repository 'unpinned_maven':
Traceback (most recent call last):
File "/private/var/tmp/_bazel_haowang/67362b0cd09d93b47f4dadb7394eed77/external/rules_jvm_external/coursier.bzl", line 837, column 38, in _coursier_fetch_impl
dep_tree = make_coursier_dep_tree(
File "/private/var/tmp/_bazel_haowang/67362b0cd09d93b47f4dadb7394eed77/external/rules_jvm_external/coursier.bzl", line 770, column 42, in make_coursier_dep_tree
return deduplicate_and_sort_artifacts(
File "/private/var/tmp/_bazel_haowang/67362b0cd09d93b47f4dadb7394eed77/external/rules_jvm_external/private/artifact_utilities.bzl", …
```
=> Fix artifact["exclusions"]

defs.bzl, private/rules/has_maven_deps.bzl
It's useful for other tools to be able to extract maven coordinates
from tags (for example, Selenium's Java Module generation) Making this
function public makes this possible.
=> Make read_coordinates public

coursier.bzl
And fall back to the slower, Starlark-based one when we either need to
survive invalid json files, or when we're using a version of bazel
that doesn't have the built-in decoder.
=> Use bazel's native json decoder where possible

private/proxy.bzl
When processing the `NO_PROXY` environment variable,
rules_jvm_exported mapped `foo.example.com,.example.com` to the JVM's
`-Dhttp.nonProxyHosts=foo.example.com|*.example.com`.  However, it
failed to map `.example.com` to `*.example.com`, because it only
remapped subdomain expressions that followed a comma.
Address this by separately handling an environment string beginning
with a ".".
Resolves #636.
=> Respect NO_PROXY=.example.com

private/pin.sh, tests/custom_maven_install/json_artifacts_testing_install.json, tests/custom_maven_install/policy_pinned_testing_install.json, tests/custom_maven_install/regression_testing_install.json, tests/custom_maven_install/unsafe_shared_cache_with_pinning_install.json
Sorting the overall list of maven libraries by coordinate gives a stable order
with locality and makes it easy to understand/review changes.
When I wrote bazelbuild/rules_jvm_external#611, I did not believe this sort was
necessary; I think because something else was already producing dependencies in
sorted order. Maybe an upgrade to coursier or something else has changed this.
Either way, explicitly sorting by .coord is idempotent at worst, and it
guarantees the output will be sorted.
Also ran the following repinning commands, not all of which changed pinned files:
```
bazel run @unpinned_maven//:pin
bazel run @unpinned_policy_pinned_testing//:pin
bazel run @unpinned_maven_install_in_custom_location//:pin
bazel run @unpinned_json_artifacts_testing//:pin
bazel run …
```
=> pin.sh: also sort dependencies by coordinate

private/tools/java/rules/jvm/external/jar/DuplicateEntryStrategy.java, private/tools/java/rules/jvm/external/jar/MergeJars.java, tests/com/jvm/external/jar/MergeJarsTest.java
It's possible to create jar files that do not unpack cleanly on
a file system. For example, they can include a _file_ named
`foo/bar` and another file called `foo`. Attempting to merge
jars by unpacking to disk and then repacking them will fail
because it's not possible to unpack cleanly.
This change does everything in-memory, without needing to create
intermediate temporary files.
=> Merge jar files without unpacking them

private/rules/java_export.bzl
One use-case is using tags=["manual"] to exclude building of these targets by default.
=> Propagate bazel tags= in java_export sub-targets

WORKSPACE, tests/unit/jvm_import/jvm_import_test.bzl
Replace with https://repo1.maven.org/maven2
Test can time out fetching from jcenter like in
https://buildkite.com/bazel/rules-jvm-external/builds/2461#c70711ec-e59f-48e9-b925-7d755a014070
It seems that in the end it is supposed to be maintained as read-only but atm times out
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
=> Don't use jcenter.bintray.com in test, it is sort of EOL

coursier.bzl, docs/api.md, private/dependency_tree_parser.bzl, private/rules/jetifier.bzl, private/rules/maven_install.bzl
Note that using package default_visibility doesn't always work so explicit visiblity attributes are needed
https://github.com/bazelbuild/bazel/issues/13681
Somewhat related to https://github.com/bazelbuild/rules_jvm_external/pull/648
In combination this for example allows to create a class_name -> maven artifact resolver for
transitive dependency classes while still keeping strict visibility (making transitive dependencies
visible only to the resolve cli tool)
=> Add new strict_visibility_value= attribute to allow exposing strict dependencies to some scopes

docs/api.md, private/rules/java_export.bzl, private/rules/pom_file.bzl
Default scope is "compile" but it could be useful to depend on other scopes like "tests"
=> Allow setting :scope via maven coords too

coursier.bzl
This makes everything work as anticipated when using Docker/arm64 linux + MacOS M1.
=> Add explicit jq-linux condition for linux_aarch64.

.bazelci/presubmit.yml, README.md
Removing 1.x, adding 4.x and 5.x
=> Set minimum Bazel support to 4.x by updating tests

README.md, coursier.bzl, private/coursier_utilities.bzl, private/rules/artifact.bzl, tests/unit/coursier_utilities_test.bzl
And add support for :type and :classifier in defs.bzl:artifact() by internally
using strip_packaging_and_classifier_and_version. To keep support for groupId:artifactId
update strip_packaging_and_classifier_and_version implementation for that case.
To be used like
```python
load("@maven//:defs.bzl", "maven_artifacts")
```
and for example
```python
load("@rules_jvm_external//:defs.bzl", "artifact")
load("@rules_jvm_external//:specs.bzl", "parse")
all_maven_targets = [artifact(a) for a in maven_artifacts if not parse.parse_maven_coordinate(a).get("classifier", "compile") in ["sources", "native"]]
java_export(
name = "maven-transitive-deps-lib",
maven_coordinates = "com.example.deps:%s:%s" % (name, "0.1"),
visibility = ["//visibility:public"],
runtime_deps = all_maven_targets,
)
```
which …
=> Expose list of all artifacts, including transitive

WORKSPACE, coursier.bzl, examples/java-export/src/main/java/com/github/bazelbuild/rulesjvmexternal/example/export/BUILD, examples/protobuf-java/WORKSPACE, examples/simple/BUILD, examples/spring_boot/WORKSPACE, private/coursier_utilities.bzl, private/dependency_tree_parser.bzl, private/rules/artifact.bzl, private/rules/has_maven_deps.bzl, private/rules/jetifier.bzl, private/rules/jvm_import.bzl, private/rules/maven_install.bzl, private/rules/maven_project_jar.bzl, tests/integration/BUILD, tests/integration/java_export/BUILD, tests/unit/artifact_utilities_test.bzl, tests/unit/coursier_test.bzl, tests/unit/coursier_utilities_test.bzl, tests/unit/manifest_stamp/BUILD, third_party/bazel_json/lib/json_parser.bzl, third_party/bazel_json/lib/json_rules.bzl, third_party/bazel_json/test/BUILD
This is a formatting-only change, created by running:
buildifier -r -lint fix  .
=> Run `buildifier`. No logical changes

private/tools/java/rules/jvm/external/jar/AddJarManifestEntry.java
This improves io performance for large jars
Running this code on my machine with a compressed 70MB zip with ~40K
entries now takes ~5s from ~25s. For the same uncompressed jar goes from ~20s to a subsecond operation.
=> Use buffered IO when writing the output jar.

private/rules/jvm_import.bzl, private/tools/java/rules/jvm/external/jar/AddJarManifestEntry.java, tests/com/jvm/external/jar/AddJarManifestEntryTest.java
There are plenty of jars out there that have an `Automatic-Module-Name`
that isn't legal. Normally, this doesn't matter too much, but when
compiling code with a modern compiler bazel will use a module path,
and that cares _a lot_, causing builds to fail.
To rectify this, we can pass an additional flag when creating the
compile jar that will strip illegal automatic module names from the
generated manifests.
=> Allow compile jars to strip illegal automatic module names

private/rules/java_export.bzl, private/rules/kt_jvm_export.bzl
I was trying to use `maven_artifacts` via `java_export` as suggested in #648, and noticed that -pom targets fail to build when they include testonly targets as deps.
I am not sure if this is a good way to resolve the issue (whether making pom target as testonly makes sense) though.
=> java_export to inherit testonly on its sub-targets

examples/scala_akka/WORKSPACE
We were using a very old version of protobuf (3.8.0-rc1) and it was in turn using a zlib version that's no longer there.
=> Upgrade protobuf version to 3.20.0

coursier.bzl, tests/bazel_run_tests.sh
Coursier respects `$XDG_CACHE_HOME` as a replacement for `$HOME/.cache`
outside of Windows and macOS.
Resolves #638.
=> Support XDG_CACHE_HOME as used by Coursier

private/tools/java/rules/jvm/external/jar/BUILD, private/tools/java/rules/jvm/external/javadoc/BUILD, private/tools/java/rules/jvm/external/maven/BUILD
And instead compile with whatever the default `--tool_java_language_version` is. Explicitly specifying a language level for individual targets should be unecessary.
I noticed this debugging https://github.com/bazelbuild/bazel/issues/15272
=> Stop hard-coding `-source 8 -target 8`

private/tools/java/rules/jvm/external/maven/MavenPublisher.java
HttpURLConnection.getErrorStream is allowed to return null, and when this happens an NPE is raised:
```
INFO: Uploading to https://...
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.NullPointerException
at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
at rules.jvm.external.maven.MavenPublisher.main(MavenPublisher.java:99)
Caused by: java.lang.NullPointerException
at rules.jvm.external.ByteStreams.copy(ByteStreams.java:26)
at rules.jvm.external.ByteStreams.toByteArray(ByteStreams.java:18)
at rules.jvm.external.maven.MavenPublisher.lambda$httpUpload$1(MavenPublisher.java:219)
at …
```
=> Don't fail if an error response is missing during publishing

coursier.bzl, tests/unit/aar_import/BUILD, tests/unit/jvm_import/BUILD
Ensures that the correct file extensions exist on the files being downloaded
https://github.com/bazelbuild/rules_jvm_external/issues/684
=> Pass downloaded_file_path to http_file

private/rules/java_export.bzl, private/rules/kt_jvm_export.bzl
This is a followup for #674.
I noticed that having `testonly=False` by default overrides packages' `default_testonly` value unnecessarily.
=> java_export: set default testonly = None

private/rules/maven_install.bzl
see https://github.com/bazelbuild/bazel/issues/5354
pinned_coursier_fetch was missed in original pr https://github.com/bazelbuild/rules_jvm_external/pull/526
=> Enable pinned_coursier_fetch to use the Starlark version of aar_import

coursier.bzl, private/java_utilities.bzl, tests/unit/java_utilities_test.bzl
This pull request is intended to fix the `java` Command-Line Argument File creation so that arguments are quoted (i.e. they are wrapped in quotes, and any quotes inside an argument are escaped). See #720 for context. In particular, this allows arguments with white space to be treated as single arguments. In particular this fixes the passing of `--credentials` arguments to coursier, which are expected to have a format like `--credentials "oss.sonatype.org alex-sonatype:aLeXsOnAtYpE"`
* See https://docs.oracle.com/en/java/javase/18/docs/specs/man/java.html#java-command-line-argument-files for the `java` Command-Line Argument File specs.
* See https://get-coursier.io/docs/other-credentials.html#inline for the coursier inline credentials format.
=> Quote java arguments written to arguments file.

private/tools/java/rules/jvm/external/jar/BUILD, private/tools/java/rules/jvm/external/jar/MergeJars.java, private/tools/java/rules/jvm/external/zip/BUILD, private/tools/java/rules/jvm/external/zip/StableZipEntry.java
This change also makes `StableZipEntry` public so that tooling
outside of rje can use it. This is already done by Selenium:
https://github.com/SeleniumHQ/selenium/blob/selenium-4.4.0/java/src/dev/selenium/tools/modules/ModuleGenerator.java#L324
=> Use stable zip entries in `MergeJars`

private/tools/java/rules/jvm/external/jar/MergeJars.java, tests/com/jvm/external/jar/MergeJarsTest.java
Without this, some tools will not correctly unpack zip
files in some cases. This also restores behaviour from
rje where we would create these intermediate folders.
=> Create empty directories in merged zip files

WORKSPACE
This should fix the failures in rules_jvm_external with Bazel@Head: https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/2613#01831092-d150-49d8-877e-102eae2c35a5
=> update bazel_skylib to latest version (1.2.1)

.bazelrc, private/tools/java/rules/jvm/external/BUILD, tests/com/jvm/external/BUILD, tests/com/jvm/external/HasherTest.java, tests/com/jvm/external/jar/BUILD, tests/com/jvm/external/javadoc/BUILD, tests/com/jvm/external/maven/BUILD, tests/integration/java_export/BUILD
We also enable strict dependencies, so we know what we
actually need to build, rather than picking up implicit
deps.
=> Pin rje to a hermetic Java 11 and use the `artifact` macro

examples/bzlmod/.bazelrc, examples/bzlmod/.bazelrc.example
The BCR tests append extra flags to it, so don't
fail when it's a symlink.
=> Make `example/bzlmod/.bazelrc` a real file

private/rules/maven_project_jar.bzl
Defers depset flattening to the execution phase in `maven_project_jar`.
=> Remove unnecessary `to_list()`

private/rules/java_export.bzl
Javadoc may have to load classes only available on the deploy_env class path in order to generate the docs.
=> Add deploy_env to java_exports's javadoc class path

private/rules/maven_project_jar.bzl, tests/integration/java_export/BUILD, tests/integration/java_export/check-deploy-env-sources.sh
The project jar has entries coming from the deploy_env filtered out. This commit ensures that the same filtering applies to source jars.
=> Filter java_export source jar based on deploy_env

private/rules/maven_project_jar.bzl
Due to https://github.com/bazelbuild/bazel/issues/15043, Bazel's native rule such as `sh_test` do not pick up `files` in `DefaultInfo` for a target in `data`. This can lead to the unexplicable absence of the jar generated by `maven_project_jar` and hence `java_export` from runfiles.
Until the upstream bug has been fixed, this is worked around by adding the files to `data_runfiles`.
=> Ensure native rules find `maven_project_jar` in runfiles

private/rules/java_export.bzl
Fixing this doesn't seem possible as `JavaRuntimeClasspathProvider` isn't visible from Java.
Also update the Bazel docs URLs.
=> Mention that `java_binary` isn't supported in `java_export` `deploy_env`

.bazelci/presubmit.yml, settings/BUILD, tests/unit/manifest_stamp/BUILD
#285 introduced `Target-Label` "stamping" that is used to produce missing strict an unused dependency warnings as described in #283. #293 changed the implementation from using `singlejar` to  `jar umf`. The implementation had a hermeticity issue and to deal with this #355 disabled the stamping and introduced an option to enable it. #468 changed the implementation to use `AddJarManifestEntry` which still had a non-determinism issue which was later described in #735.
I believe the non-determinism in `AddJarManifestEntry` was fully resolved in #738 so this change re-enables the stamping by default, but in case I missed something keeps the option to disable it. A later release can remove the option completely.
The change also re-enables the test that was set to `manual` in #355.
Closes #283.
=> Enable manifest stamping by default

coursier.bzl
`.removeprefix` was only added to starlark on bazel 5, so this fails on bazel 4.
=> fix: provide our own remove_prefix implementation

private/tools/java/rules/jvm/external/jar/MergeJars.java, tests/com/jvm/external/jar/MergeJarsTest.java
Prior to this change, the list of created directories was populated as we _read_ the inputs. This meant that the output jars would not have these directories re-created. Oops.
=> Ensure missing directories are added to zips

README.md
These are documented in Bazel's docs, but we should also document that here as well.
=> Add instructions for IPv6 support in rules_jvm_external.

README.md
Adds a section to the `README.md` discussing errors stemming from a machine being configured to use a non-standard JDK as its default. The recommended solution is to explicitly use OpenJDK instead.
=> Add section re: issues with nonstandard JDKs.

README.md
Tests will fail unless there is an Android SDK available on the system. This PR documents the Android SDK requirement in the "Tests" section of `README.md`.
See: https://github.com/bazelbuild/rules_jvm_external/issues/763
=> Document Android SDK dependency for tests

private/rules/maven_publish.bzl
Issue: https://github.com/bazelbuild/rules_jvm_external/issues/618
Solution:
Expand maven version using bazel variables to publishing maven artifact to repo.
bazel run --stamp \
--define "maven_repo=<> \
--define "maven_user=<>" \
--define "maven_password=<>" \
--define "maven_version=<>" \
//src/main/java/com/xxx/example:<targt>
=> maven version expanded

private/pin.sh, tests/bazel_run_tests.sh
Attempting to address https://github.com/bazelbuild/rules_jvm_external/issues/800 for Bazel HEAD which has added caching for print statements.
It also sends all output from the tests to $TEST_LOG so it does go to stdout when the tests are run.
=> For m2local integration tests send all output to test log and clear cache before each test to prevent caching of print output

coursier.bzl, private/proxy.bzl, tests/unit/proxy_test.bzl
Remove single-quoting of the `-Dhttp.nonProxyHosts` argument as this arg may be spilled over to an argsfile, where quoting is considered by the JVM as part of the host expression.  (I expect the single-quoting to be unnecessary in the pre-Java9+ path, as my understanding of `rctx.execute` is that Bazel _doesn't_ use the shell, so special chars like pipes, etc. are harmless.)
Resolves #780.
=> fix NO_PROXY handling under Java 9+

.allstar/binary_artifacts.yaml
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/808
=> Add ignorePaths for allstar binary artifacts check.

coursier.bzl
Fixes #824.
Ideally, this would use paths.normalize in skylib, but that would require changes to how rules_jvm_external setups up dependencies.
=> Normalize path returned by get_coursier_cache_or_default in _relativize_and_symlink_file_in_coursier_cache

.bazelci/presubmit.yml, README.md, WORKSPACE, coursier.bzl, docs/api.md, private/extensions/maven.bzl, private/rules/maven_install.bzl, tests/bazel_run_tests.sh, tests/unit/build_tests/BUILD
This feature wasn't being tested properly, so we had no way of determining whether it would work. For the case of pinning artifacts (which is the recommended approach) it's possible to use the `COURSIER_CACHE` env var to still use the shared cache.
=> Remove the `unsafe_shared_cache` option

private/rules/v1_lock_file.bzl, private/tools/java/rules/jvm/external/maven/Outdated.java
`sp` is usually used for Service Pack and doesn't mean the release is a pre-release.
=> Remove 'sp' from MAVEN_PRE_RELEASE_QUALIFIERS for outdated

README.md, docs/bzlmod.md
This would be useful for a training course I'm teaching, as well as casual users who are giving this a try.
=> docs: add documentation for starting with bzlmod

README.md
The feature was removed in https://github.com/bazelbuild/rules_jvm_external/pull/834
=> Remove broken README link to Persistent Artifact Cache

examples/android_instrumentation_test/.bazelrc
Bazel is removing support for Python 2
Fixes #846
=> Remove --host_force_python from example bazelrc

private/rules/maven_bom.bzl, tests/integration/maven_bom/bom-dependencies.golden.xml, tests/integration/maven_bom/transitive-bom-dependencies.golden.xml
*sigh* How did I miss this before? The dependencies BOM attempted to import itself, rather than the BOM that contained the primary deps. This PR fixes that.
=> Fix dependencies BOM so it does not include a circular dep

coursier.bzl, private/proxy.bzl, tests/unit/proxy_test.bzl
In coursier version v2.1.0-M7 and later there was a [change to the proxy setup](https://github.com/coursier/coursier/pull/2440) that requires `http.proxyProtocol` or `https.proxyProtocol` to be set for the proxy to work.  I created https://github.com/coursier/coursier/pull/2701 to fix this, but until that is merged we need to set the values in our proxy settings.
This PR also adds better verbose logging for args_files.
=> Set http.proxyProtocol and https.proxyProtocol for coursier

WORKSPACE, private/dependency_tree_parser.bzl, tests/unit/build_tests/BUILD
When `generate_compat_repositories` is True, the `jvm_import` target  is not visible to the compat alias, causing an error when trying to use the compat label.
```
jvm_import(
name = "com_google_j2objc_j2objc_annotations",
visibility = ["//visibility:private"],
tags = ["maven_coordinates=com.google.j2objc:j2objc-annotations:1.3", "maven_url=<>/j2objc-annotations-1.3.jar"],
jars = ["@maven//:<>/j2objc-annotations-1.3.jar"],
srcjar = "@maven//:<>/j2objc-annotations-1.3-sources.jar",
deps = [],
)
alias(
name = "jar",
visibility = ["//visibility:public"],
actual = "@maven//:com_google_j2objc_j2objc_annotations",
)
```
I propose adding the alias path to the visibility of the `jvm_import` when compat repositories are being generated.
=> transitive dependencies should be visible to their compat alias

docs/bzlmod.md
I think it's better for readers to NOT have an (ancient) version in an example, and let them go look it up.
At least I for one was too stupid to notice that inline `FIXME` and it caused me https://github.com/bazelbuild/rules_jvm_external/issues/872 pain.
Explicitly documenting how and where one has to go look up the correct version seems preferable.
=> docs: Remove hard-coded version in bazel_dep example

coursier.bzl
Sometimes, some issue lead to the `pinned_maven_install()` function being completely empty, making the defs.bzl file syntactically incorrect, causing all sorts of issues making it hard to recover (needing a `bazel clean --expunge` or a manual edition of the file to fix the syntax).
This prevents that kind of situation.
=> Handle the case where dependencies are empty

private/extensions/maven.bzl
Test case same as #876 but overriding with patch 
```sh
mkdir test_bzlmod
cd test_bzlmod
touch BUILD WORKSPACE WORKSPACE.bzlmod  
cat << EOF > MODULE.bazel 
bazel_dep(name = "rules_jvm_external", version = "5.1")
git_override(
module_name = "rules_jvm_external",
remote = "https://github.com/yrom/rules_jvm_external.git",
commit = "e4dac53947fa2e664ecc3fcaf94121eeccb1015b",
)
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
name = "androidx",
artifacts = [
"androidx.appcompat:appcompat:1.4.0",
],
repositories = [
"https://maven.google.com",
"https://repo1.maven.org/maven2",
],
excluded_artifacts = [
"com.android.support:support-v4",
"com.android.support:support-annotations",
],
jetify = True,
)
use_repo(maven, "androidx")
EOF
echo "common …
```
=> Fixed #876, the 'excluded_artifacts' should be formatted in json spec

private/versions.bzl
v2.1.2 contains an OOM fix while collecting transitive deps. It also speeds up resolution time.
https://github.com/coursier/coursier/releases/tag/v2.1.2
https://github.com/coursier/coursier/pull/2580
Before:
$ bazelisk run @unpinned_regression_testing//:pin
INFO: Analyzed target @unpinned_regression_testing//:pin (1 packages loaded, 3 targets configured). INFO: Found 1 target...
Target @unpinned_regression_testing//:pin up-to-date:
bazel-bin/external/unpinned_regression_testing/pin
INFO: Elapsed time: 17.980s, Critical Path: 0.01s
After:
$ bazelisk run @unpinned_regression_testing//:pin
INFO: Analyzed target @unpinned_regression_testing//:pin (26 packages loaded, 99 targets configured). INFO: Found 1 target...
Target @unpinned_regression_testing//:pin up-to-date: …
=> Bump to Coursier v2.1.2.

private/rules/maven_publish.bzl
Artifactory uses [semicolons in URLs to set properties](https://jfrog.com/help/r/jfrog-artifactory-documentation/using-properties-in-deployment-and-resolution). Currently, when trying to use a maven_repo with semicolons in `maven_publish`, they are interpreted as statement terminators by bash. This PR adds quotes to all the arguments to {uploader} to solve this.
=> Allow semicolons in maven_repo

private/rules/jetifier.bzl, private/rules/maven_install.bzl
AndroidX is a series of dependencies that Google released, like standard libraries but for all things Google. At some point they switched the namespace on those libraries to `androidx`, which caused a ton of runtime crashes because you'd have older versions of libraries that hadn't updated to Androidx conflicting with ones that have updated.
The last release of jetifier was in 2020, and since then the tool has been deprecated & so we should also mark it as deprecated and remove from rules_jvm_external a future release.
=> Deprecate jetify

private/rules/maven_bom.bzl, private/rules/maven_bom_fragment.bzl, private/rules/pom_file.bzl
#794 missed adding template expansion in a few places where Maven coordinates are used. This PR covers the remaining usages.
=> Expand template variables in coordinates in additional places

private/rules/maven_project_jar.bzl
Any rule which uses java_common should register java toolchain_type.
=> Register java toolchain inside maven_project_jar

coursier.bzl, private/extensions/maven.bzl
Fixes the `bazel run` command suggested when the lockfile is outdated and Bzlmod is used.
=> Fix pinning error with Bzlmod

README.md, docs/api.md, private/rules/java_export.bzl, private/rules/maven_publish.bzl, private/tools/java/com/github/bazelbuild/rules_jvm_external/maven/MavenPublisher.java, tests/integration/java_export/PublishShapeTest.java
This PR fixes #679 by allowing users to specify `maven_user` and `maven_pass` via environment variable when using `maven_publish`.
=> Allow passing sensitive credentials for java_export with environment variables

docs/api.md, examples/java-export/BUILD, examples/java-export/src/main/java/com/github/bazelbuild/rulesjvmexternal/example/export/BUILD, private/rules/java_export.bzl, private/rules/maven_publish.bzl, private/tools/java/com/github/bazelbuild/rules_jvm_external/maven/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/maven/MavenPublisher.java, tests/integration/java_export/PublishShapeTest.java
This PR addresses the remaining issues in #805 which got pretty close to being mergeable. I also renamed "extra_artifacts" to "classifier_artifacts" to stick closer to Maven terminology. Also, since javadocs and source jars are special cases of classifier artifacts, I refactored them to use the same code path.
=> Add classifier_artifacts parameter to java_export to allow users to publish extra artifacts

CODEOWNERS
Only @cheister was getting owners review because GitHub doesn't support multiline aggregation and took the last row :-)
@Wyverald let me know if you'd still like to be in RJE's CODEOWNERS.
=> Fix CODEOWNERS only requesting reviews from @cheister

private/tools/java/com/github/bazelbuild/rules_jvm_external/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/BUILD
Modern JDKs print a warning that Java 8 support is deprecated and will be removed in a future release. To prevent that warning being displayed, we add an additional `javac` flag when compiling the code which targets Java 8.
The long-term solution is to only target Java 11+, which I suggest we do after Java 21 ships in Septembe after 2023.
=> Prepare for Java 8 support dropping from modern JDKs

private/extensions/maven.bzl
Fix the following error when using `test_only` in Bzlmod
```
ERROR: Traceback (most recent call last):
File "/private/var/tmp/_bazel_pcloudy/829441223e9fec5a5a2e3d1dd743fdf0/external/rules_jvm_external~5.2/private/extensions/maven.bzl", line 304, column 52, in _maven_impl
artifacts_json = [_json.write_artifact_spec(a) for a in artifacts]
File "/private/var/tmp/_bazel_pcloudy/829441223e9fec5a5a2e3d1dd743fdf0/external/rules_jvm_external~5.2/specs.bzl", line 230, column 38, in _artifact_spec_to_json
"\", \"version\": \"" + artifact_spec["version"] + "\""
Error: unsupported binary operation: string + bool
```
=> Fix `testonly` attribute handling

private/rules/javadoc.bzl
javadoc may have to inspect compile-only dependencies.
Also removes a line that only added elements to a depset that are already contained in this depset.
=> Add compile-only deps to javadocs classpath

private/dependency_tree_parser.bzl
Verified manually:
```
filegroup(
name = "aopalliance_aopalliance_javadoc",
srcs = ["None"],
tags = ["javadoc"],
visibility = ["//visibility:public"],
)
```
=> Sets javadoc filegroup targets generated from maven_install to include visibility = //visiblity:public (#942)

private/dependency_tree_parser.bzl, tests/unit/jvm_import/jvm_import_test.bzl
This may help folks to do things like generate sbom files by looking at the attributes of jvm_import targets.
=> jvm_import: Include sha256 in tags

README.md, docs/bzlmod.md, examples/bzlmod/MODULE.bazel
I initially struggled with how apply the workaround from https://github.com/grpc/grpc-java/issues/10576 for my https://github.com/enola-dev/enola/pull/295; hopefully this docs enhancement helps others later.
@ejona86 FYI
=> docs: Clarify how to use exclusions with bzlmod

.bazelci/presubmit.yml
Also disable Android platforms, see #978.
=> Split Android tests into a separate task.

private/tools/java/com/github/bazelbuild/rules_jvm_external/zip/StableZipEntry.java, tests/integration/java_export/PublishShapeTest.java
It's a bit weird that the jars created by `maven_project_jar` have timestamps from 1985, but the outputs from `java_library` are from 2010. Time to make them the same.
=> Normalise timestamps from maven_project_jar with those from java_library

private/tools/java/com/github/bazelbuild/rules_jvm_external/jar/BUILD
A [recent JDK update](https://github.com/openjdk/jdk/commit/84f23149e22561173feb0e34bca31a7345b43c89#diff-7313eb3d328797a7720fa1b2b73cd159934506593443e45534baad80cb1382b7R924-R927) started printing the following warning message from the JVM
```
[warning][perf,memops] Cannot use file /tmp/hsperfdata_username/2 because it is locked by another process (errno = 11)
``` 
on linux hosts.  Also referenced from https://github.com/bazelbuild/bazel/issues/3236
This PR disables the perfdata generation when stamping a jar so we won't get this warning message, which is printed for every jar that processed.
=> Disable JVM perfdata when stamping jars

coursier.bzl
Let's assume `maven_install(name = "maven")`.
- `@unpinned_maven//:pin` is created iff `maven_install_json` is specified.
- When the lockfile got corrupted (hash recorded in the file was different than the result of hashing the file), we instructed the user to remove the `maven_install_json` attribute.
- We then instructed the user to run `@unpinned_maven//:pin`.
- Because the `maven_install_json` attribute was removed ,`@unpinned_maven` was not created, resulting in a crash.
We treat hash integrity as if it were any other error in the lockfile, and instruct the user to repin by setting `fail_if_repin_required=False`.
=> fix: Correct repin instructions when lockfile integrity is compromised

coursier.bzl, private/dependency_tree_parser.bzl, private/rules/v1_lock_file.bzl, private/rules/v2_lock_file.bzl, tests/bazel_run_tests.sh
Coursier can resolve m2local artifacts when pinning. However, if you try using them, they will fail stamping:
```
Stamping the manifest of @maven//:dev_zio_zio_test_2_12 failed: missing input file 'external/maven/dev/zio/zio-test_2.12/2.0.18-RC0-whatever/zio-test_2.12-2.0.18-RC0-whatever.jar', owner: '@maven//:dev/zio/zio-test_2.12/2.0.18-RC0-whatever/zio-test_2.12-2.0.18-RC0-whatever.jar'
```
This is assuming, that I have built dev.zio:zio-test-junit_2.12:2.0.18-RC0-whatever locally, deployed it to ~/.m2/repository and then set up a dependency on it, enabled m2local and tried using the artifact.
There are two reasons to that:
1. In coursier.bzl we are not adding a local url to the generated http_file() usage (so it does not download it)
2. A corresponding genrule entry is not generated …
=> m2local: solve files not getting resolved

private/tools/java/com/github/bazelbuild/rules_jvm_external/maven/MavenPublisher.java
Fix an `ArrayIndexOutOfBoundsException` when publishing an artifact without additional classifiers.
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
at com.github.bazelbuild.rules_jvm_external.maven.MavenPublisher.main(MavenPublisher.java:109)
```
Fixes #1010
=> fix: Publish artifacts without additional classifiers

MODULE.bazel, docs/api.md, private/extensions/maven.bzl
=> Allow `bzlmod`-based builds to set repin instructions

.bazelrc
After https://github.com/bazelbuild/rules_jvm_external/pull/1038, we no longer need this .bazelrc setting
=> Since we removed rules_js, we can remove the bazelrc setting for it

scripts/BUILD, scripts/mirror_coursier.sh
The script was referencing a location in `$output_base/execroot/external` that no longer existed after the switch to bzlmod. The version number is also no longer in the pathname, so load it from versions.bzl directly.
=> Fix mirror_coursier script

docs/api.md, private/rules/java_export.bzl, private/rules/maven_project_jar.bzl, tests/integration/java_export/BUILD, tests/integration/java_export/check-manifest-lines-added-MANIFEST.MF.golden
Allows users to add specific manifest line to the jars generated by `java_export`. This is similar to the `deploy_manifest_lines` from `java_binary`, but features a dict instead of a list, since it's really a key/value pair.
=> Add `manifest_entries` to `java_export`

private/tools/java/com/github/bazelbuild/rules_jvm_external/jar/MergeJars.java, tests/com/github/bazelbuild/rules_jvm_external/jar/MergeJarsTest.java
maven_project_jar has a jar combining action which is attempting
to exclude dependencies' contents from the jar. However this also
removes LICENSE file from the Jar file since it is quite common for
external dependencies to include as well.
This is similar to META_INF case which the jar merging tool is special
casing and the PR piggy backs on that special case.
=> Do not remove LICENSE files when combining jars

private/coursier_utilities.bzl, private/dependency_tree_parser.bzl
I think it would be a bit nicer to set up the data dependencies in the generated rules, but I wasn't able to get it working when trying a combination of cc_import, java_library, etc. The downside of doing that is we wouldn't be able to use `select` to depend on just the platform-specific jar that we want. 
If anyone has ideas how to do better, let me know!
=> Support so/dylib/dll packaging types

private/rules/jvm_import.bzl
This ensures that the AddJarManifestEntry jar used in the `jvm_import` actions is executed with the jdk version set by the downstream project's language version (which was used to correctly build the jar itself), which resolves to the right toolchain, instead of using whatever `@local_jdk` resolves to.
This fixes the case where the jar is built with a newer JDK version/lang level, but executed with an older runtime.
Unblocks Bazel's JDK 21 upgrade.
Fixes #895
=> Make jvm_import use `java` from resolved toolchain instead of host machine.

private/rules/jvm_import.bzl
PR #1058 made the `jvm_import` actions use Java toolchains rather than host tools, but chose the runtime used to run `javac` instead of the runtime used to run build tools. The latter can be configured via `--tool_java_runtime_version` while the former is fixed in the Java compilation toolchain.
=> Use tool instead of compilation runtime in `jvm_import` actions

private/extensions/maven.bzl
This fixes an issue where the longest timeout wasn't actually being used. 
I haven't observed this actual problem, but just noticed that timout was an unused variable in the code, and it seems highly likely the intention was to have `timeout` here instead.
=> Fix timout->timeout typo

private/java_utilities.bzl, tests/unit/java_utilities_test.bzl
Fedora Linux has updated its latest JDK to version `22-ea` and that breaks the version parsing routine on here. 
```
zsh❯ java --version
openjdk 22-ea 2024-03-19
OpenJDK Runtime Environment (Red_Hat-22.0.0.0.36-1) (build 22-ea+36)
OpenJDK 64-Bit Server VM (Red_Hat-22.0.0.0.36-1) (build 22-ea+36, mixed mode, sharing)
zsh❯ which java
/usr/lib/jvm/java-22-openjdk/bin/java
```
The rewritten version parser should adapt better.
=> fix: determine the version of java correctly

examples/android_local_test/.bazelrc, examples/kt_android_local_test/.bazelrc
Both android_local_test and kt_android_local_test are failing to:
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //src/test:main_activity_test
-----------------------------------------------------------------------------
JUnit4 Test Runner
java.lang.UnsupportedOperationException: The Security Manager is deprecated and will be removed in a future release
at java.base/java.lang.System.setSecurityManager(System.java:429)
at com.google.testing.junit.runner.junit4.JUnit4Runner.installSecurityManager(JUnit4Runner.java:256)
at com.google.testing.junit.runner.junit4.JUnit4Runner.run(JUnit4Runner.java:113)
at com.google.testing.junit.runner.BazelTestRunner.runTestsInSuite(BazelTestRunner.java:145)
at com.google.testing.junit.runner.BazelTestRunner.main(BazelTestRunner.java:76) …
```
=> Fix examples build breakage with SecurityManager usage in examples apps.

examples/android_local_test/.bazelrc, examples/kt_android_local_test/.bazelrc
Reverts bazelbuild/rules_jvm_external#1073
This is no longer needed since we disabled the macOS tests.
=> Revert "Fix examples build breakage with SecurityManager usage in examples apps."

private/tools/java/com/github/bazelbuild/rules_jvm_external/Coordinates.java, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/ResolverTestBase.java
The behaviour exhibited by both `coursier` and `gradle` is that when a dependency graph contains anything with the same `groupId:artifactId` and a higher version, the higher version is selected, so we're going to settle on this as what's expected.
In addition, our lock file relies on the `groupId:artifactId` to always have the same version too, so that's another reason to follow what `gradle` and `coursier` do.
`maven` will quite happily (and correctly IMO) include deps at different versions if their classifiers differ, which is different from that behaviour. Work around that by revising values in the build graph.
=>  [maven] Handle the case where a resolution contains an artifact with differing classifiers at different versions

.bazelci/examples.yml
The CI tests are failing again.
=> Temporarily turn down android_local_test examples builds on macOS

private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/ResolverTestBase.java
Add logging so you can see how many dependencies are being resolved by the maven resolver and when the env var RJE_VERBOSE is set it will print the resolved dependency graph and remappings
e.g. 
```
> RJE_VERBOSE=1 bazel run @maven_resolved_with_boms//:pin
...
Currently: resolving 1 bom artifacts
...
Currently: resolving and fetching the transitive closure of 6 artifact(s)
...
Dependency Graph:
com.google.auto.value:auto-value-annotations:jar:1.6.3 [runtime]
net.sf.json-lib:json-lib:jar:jdk15:2.4 [runtime]
+- commons-beanutils:commons-beanutils:jar:1.8.0 [runtime]
|  \- commons-logging:commons-logging:jar:1.1.1 [runtime] (nearer exists)
+- commons-collections:commons-collections:jar:3.2.1 [runtime]
+- commons-lang:commons-lang:jar:2.5 [runtime]
+- commons-logging:commons-logging:jar:1.1.1 …
```
=> Add logging to maven resolver for number of artifacts being resolved and RJE_VERBOSE will log the entire dependency graph

private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/events/EventListener.java, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/BUILD.bazel, tests/com/github/bazelbuild/rules_jvm_external/resolver/DelegatingListener.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/MavenResolverTest.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/ResolverTestBase.java
Maven does not fail when a transitive dependency is missing.  It prints out a warning similar to
```
[WARNING] The POM for org.mortbay.jetty:jetty:jar:6.1.26.cloudera.2 is missing, no dependency information available
```
this PR implements the same behavior for the maven resolver.
This changes the manageDependencies generation to match on all artifact fields groupId:artifactId:extension:version:classifier instead of just groupId:artifactId
=> Handle maven artifact not found

private/tools/java/com/github/bazelbuild/rules_jvm_external/jar/MergeJars.java
Addresses https://github.com/bazelbuild/rules_jvm_external/issues/1106
=> Add an exception for COPYRIGHT and NOTICE files in the same way as LICENSE

coursier.bzl, private/java_utilities.bzl, tests/unit/java_utilities_test.bzl
https://github.com/bazelbuild/rules_jvm_external/pull/1069 broke the case where `java -version` returns 
```
Picked up _JAVA_OPTIONS:
```
in the first line of the version string
=> Fix java version parsing when _JAVA_OPTIONS are returned from 'java -version'

coursier.bzl, private/java_utilities.bzl, tests/unit/java_utilities_test.bzl
Since we moved the [minimum supported Java version to 11 ](https://github.com/bazelbuild/rules_jvm_external/pull/972)we no longer need to check for argsfile support on Java version 8.
=> Since we now require Java 11 we don't need to check for java 8 when building an argsfile

private/rules/has_maven_deps.bzl, private/rules/java_export.bzl, private/rules/maven_utils.bzl, private/rules/pom_file.bzl
We are migrating a Gradle project to Bazel and can't break compatibility with other Java repos that import the Maven artifacts.
[Gradle has a concept](https://developer.android.com/build/dependencies#dependency_configurations) of `implementation` dependencies. These dependencies are available at compile time when building the library, but are given a `runtime` scope in the generated `pom.xml` file for consumers of the library to avoid leaking the dependency to the consumers at compile time.
This adds a list to `java_export` called `implementation_deps`. The targets passed here and in `deps` will be given a `runtime` scope on the generated `pom.xml`, but will still be available at compile time to the java_library like normal `deps`. It only impacts pom generation.
This is different than …
=> Add an `implementation_deps` argument to java_export

private/dependency_tree_parser.bzl
I noticed the refactor of `dependency_tree_parser.bzl` in https://github.com/bazelbuild/rules_jvm_external/pull/994 might have unintentionally omitted a line that added target labels to the set of `seen_imports`. This line is present in [v5.3](https://github.com/bazelbuild/rules_jvm_external/blob/5.3/private/dependency_tree_parser.bzl#L155-L156), but then removed in [v6.1](https://github.com/bazelbuild/rules_jvm_external/blob/6.1/private/dependency_tree_parser.bzl#L457).
I believe this removal was accidental, as it is now possible for `maven_install` to create a generated BUILD file which contains multiple copies of a target with the same name, which is an invalid state.
This PR restores the missing call to `seen_imports[target_label] = True`.
=> Restore Target Uniqueness Guard in dependency_tree_parser.bzl

.bazelrc, private/pin.sh, private/rules/coursier.bzl
Bazel upstream is planning to flip `--experimental_sibling_repository_layout` to True, which moves the external repositories from `execroot/_main/external/<repo>` to `execroot/<repo>`, thereby freeing up `//external` as a package name.
This change adds the flag to RJE's own bazelrc. The only failure found so far is the `external/` hardcode in `pin.sh`. 
TEST: `tests/bazel_run_tests.sh`.
```
$ ./tests/bazel_run_tests.sh
Running bazel run tests:
test_maven_resolution PASSED
test_dependency_aggregation PASSED
test_duplicate_version_warning PASSED
test_duplicate_version_warning_same_version PASSED
test_outdated PASSED
test_outdated_no_external_runfiles PASSED
test_m2local_testing_found_local_artifact_through_pin_and_build PASSED
test_unpinned_m2local_testing_found_local_artifact_through_pin_an …
```
=> Enable --experimental_sibling_repository_layout in bazelrc 

README.md, repositories.bzl
It seems setting `repositories` is not sufficient to use customized repository because `@rules_jvm_external//:rules_jvm_external_deps_install.json` will always be picked up.
=> fix: Use customized repositories

private/rules/coursier.bzl
Coursier fails with a cryptic error in case someone tries to use `maven_install()` without specifying any `repositories`, which is a small silly thing I did when trying to extract internal corporate code into a public proof-of-concept on how to do something with Bazel that took me 10 minutes to hunt down :)
When `repositories` is empty, Coursier fails with an error like:
```
Dependencies:
org.junit.jupiter:junit-jupiter-engine:5.10.2:
Resolution error: Error downloading org.junit.jupiter:junit-jupiter-engine:5.10.2
```
this was for a `maven_install()` block with a single artifact to install; otherwise the error message will contain one `Resolution error` per artifact. The problem though is that Coursier doesn't say what the error is, just that one occurred.
The root-cause is that …
=> maven_install: fail if 'repositories' attribute is empty

README.md, repositories.bzl
This allows people to repin these deps locally if needed, assuming they don't want to use Bazel's `--experimental_downloader_config` flag.
`bzlmod` users can achieve the same result by specifying an `install` tag in their root level module and overriding the required fields.
=> Allow `rules_jvm_external`'s own deps's lock file to be overridden

private/extensions/maven.bzl, private/rules/coursier.bzl, private/rules/maven_install.bzl
The primary use case this change tries to solve is passing down `--max-iterations` to coursier because the default value could be too small for certain artifacts.
=> feat: Pass additional coursier cli options

docs/bzlmod.md
=> remove old comment about grpc-java and bzlmod

docs/api.md
Follow up to https://github.com/bazelbuild/rules_jvm_external/pull/1137 that adds the new options to the documentation
=> Add documentation for additional_coursier_options

private/rules/coursier.bzl
The below error will be gone with the fix.
```
MODULE.bazel.lock is no longer up-to-date because: The implementation of the extension 'ModuleExtensionId{bzlFileLabel=@@rules_jvm_external~//:extensions.bzl, extensionName=maven, isolationKey=Optional.empty}' or one of its transitive .bzl files has changed,The repo mappings of certain repos used by the extension 'ModuleExtensionId{bzlFileLabel=@@rules_jvm_external~//:extensions.bzl, extensionName=maven, isolationKey=Optional.empty}' have changed. Please run `bazel mod deps --lockfile_mode=update` to update your lockfile.
```
=> Fix bzlmod lockfile always not up-to-date

private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java
Address https://github.com/bazelbuild/rules_jvm_external/issues/1161 with verbose logging since I don't think overriding a version from dependencyManagement is uncommon in Maven.
=> Add RJE_VERBOSE output when a BOM version is overridden by an explicit dependency

private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java
Follow up to comment in https://github.com/bazelbuild/rules_jvm_external/pull/1172.  I think the peek is cleaner so the logging is separated from the filter logic
=> Use peek for verbose logging instead of combining it in the filter clause

private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/ResolverTestBase.java
We only allow one version for a dependency and all of its classifier in our json file.  If a dependency is declared with different classifiers and different versions then we still want to resolve the same version of the dependency for all of the classifiers.
For example, if you had the dependencies
"io.netty:netty-tcnative-boringssl-static:osx-aarch_64:2.0.61.Final",
"io.netty:netty-tcnative-boringssl-static:2.0.47.Final",
we want only one version to be resolved in the json file
```
"artifacts": {
"io.netty:netty-tcnative-boringssl-static": {
"shasums": {
"jar": "b6f974972c44cd6f9cecabc255290286faac40b6393c66c3c3c0db7f421cc28e",
"linux-aarch_64": "3614395218ae379cec22ccaa089c4f27b9329a660e0d53c93e7cb12b7a2cee46",
"linux-x86_64": "4ff9d14f1ec6ccee35b78f53a6f3d9c7c54535aa2a76138311c2f619c5e1 …
```
=> Consolidate maven versions of classifiers for an artifact

MODULE.bazel, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java
This was inspired by https://github.com/bazelbuild/rules_jvm_external/issues/1168
Unfortunately it doesn't it fix it for all uses since the real fix is updating all of the bazel dependencies that use protobuf 21.7, but it does fix it for rules_jvm_external development and testing.
=> Update protobuf to version that does not define @maven repo in it's MODULE.bazel

README.md
Fixes the table of contents bzlmod link now that the heading changed to "Bazel 7 and above".
=> Fix TOC entry for bzlmod usage

docs/bzlmod.md
There was a Google-internal query about how the install and artifact tags interact with each other, and when to use one or the other.
=> Add a `maven.artifact` tag example into the bzlmod readme.

docs/bzlmod.md
This is no longer needed as of version 6.1, thanks to:
- https://github.com/bazelbuild/rules_jvm_external/pull/1112
Attn: @shs96c
=> Update bzlmod.md to remove unpinned_maven

private/extensions/maven.bzl, private/rules/coursier.bzl, private/rules/maven_install.bzl
Doing this by performing string interpretation on the repo name is a bit
brittle. And it works less well under Bzlmod where the unpinned repo
name is going to look something like
`rules_jvm_external~~maven~unpinned_maven`.
After this change, the lockfile pinning script, `@maven//:pin` will use the local
machine's Coursier cache (`~/Library/Caches/Coursier` on MacOS) even under
Bzlmod. A populated cache makes version resolutions substantially faster to obtain.
=> Track whether a repo is pinned or unpinned by explicit attr

tests/integration/BUILD, tests/integration/override_targets/override_contains_additional_deps.sh
The delimiter used in canonical repo names is changing from `~` to `+`.[^1] In this logic, which tries to normalize query results for the purposes of diff-testing against golden results, label parsing seems unavoidable. So we fall back to the non-preferred approach of supporting both delimiters in our patterns.
Also, refine the patterns to be more exact and better reflect the intent to only act agaisnt the repo-name part of each label:
* anchor the patterns to match only at start of each label
* only operate before the first `/`
[^1]: https://github.com/bazelbuild/bazel/issues/23127
=> Support  plus as repo name delimiter in query-result normalization logic

private/extensions/maven.bzl
This input is entirely ignored. The `maven.install` tag is the only place repositories may be specified.
Closes #1200
=> Remove repositories attr from maven.artifact

MODULE.bazel, examples/java-export/.bazelrc, private/tools/java/com/github/bazelbuild/rules_jvm_external/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/BUILD, repositories.bzl
rules_java 7.10.0 work with Bazel 7 down to Bazel 6.2.0. This makes it possible to load symbols like JavaInfo from rules_java also on older Bazel versions (previous Java releases didn't have Java/common/java_info.bzl file). A single rules_java version for multiple Bazel releases should also simplify things.
Remove the flag --release, because it breaks on the combination of Bazel 6.x and rules_java 7.10.0, most likely because of incompatible changes in the turbine. The flag is not necessary, because the release is already controlled --java_release_version flag.
=> Upgrade rules_java to 7.10.0

private/rules/jvm_import.bzl
We only allow a single `srcjar`, and the `jars` parameter is already checked to ensure the length is 1.
This also deprecates the original `jars` parameter.
=> Allow `jvm_import` to accept a `jar` parameter

BUILD, MODULE.bazel, WORKSPACE, private/dependency_tree_parser.bzl, private/lib/coordinates.bzl, private/lib/urls.bzl, private/rules/coursier.bzl, private/rules/java_export.bzl, private/rules/jvm_import.bzl, private/rules/maven_bom.bzl, private/rules/maven_project_jar.bzl, private/rules/maven_utils.bzl, providers.bzl, repositories.bzl, tests/unit/jvm_import/jvm_import_test.bzl
The Bazel community is heading towards using `@rules_license` as the basis for SBOM generation. Providing `PackageInfo` for the dependencies we import from Maven provides a part of the puzzle of how to make this work.
=> Make our rules output `PackageInfo` where possible

private/rules/java_export.bzl
There is a difference between `None` (where we get the default values of a rule attribute) and `[]` (which is also "falsey" but not `None`)
=> Fix javadoc generation

private/rules/kt_jvm_export.bzl
Use Label so that the reference is resolved within the context of rules_jvm_external module and not in the calling workspace
---
In our workspace we include @rules_kotlin under a different name, and without this fix, @rules_kotlin is not resolved as intended.
=> Fix @rules_kotiln reference in kt_jvm_export

README.md, private/rules/coursier.bzl
With Bzlmod, only the root module can refer to its own repo via `@//`. Instead, modules should just use repo-relative labels to refer to themselves, which works even if they aren't the root module.
Avoids this warning with Bazel 8:
```
WARNING: The module extension @@rules_jvm_external+//:extensions.bzl%maven produced an invalid lockfile entry because it referenced @@[unknown repo '' requested from @@rules_jvm_external+]. Please report this issue to its maintainers.
```
=> Do not use or recommend `@//` labels with Bzlmod

docs/api.md, private/rules/maven_bom.bzl, tests/integration/maven_bom/BUILD, tests/integration/maven_bom/substitution-bom.golden.xml
e.g. to pass a config setting for variabel substitution
```starlark
string_flag(
name = "version",
build_setting_default = "0.0.0-dev",
make_variable = "VERSION",
visibility = ["//visibility:public"],
)
maven_bom(
name = "bom",
dependencies_maven_coordinates = "com.examplet:bom:$(VERSION)",
java_exports = [
],
maven_coordinates = "com.examplet:bom:$(VERSION)",
toolchains = [":version"],
)
```
=> pass toolchains to maven_* rules

private/rules/coursier.bzl, private/rules/java_export.bzl, private/tools/java/com/github/bazelbuild/rules_jvm_external/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/coursier/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/jar/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/javadoc/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/maven/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/cmd/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/events/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/netrc/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/remote/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/ui/BUILD, private/tools/java/com/github/bazelbuild/rules_jvm_external/zip/BUILD, scripts/BUILD, tests/com/github/bazelbuild/rules_jvm_external/manifest/BUILD, tests/com/github/bazelbuild/rules_jvm_external/resolver/BUILD, tests/integration/BUILD, tests/integration/java_export/BUILD, tests/integration/maven_bom/BUILD, tests/integration/override_targets/BUILD, tests/integration/plugin_targets/BUILD, tests/unit/exports/BUILD, tests/unit/exports/exports_test.bzl, tests/unit/jvm_import/BUILD
* Upgrade to the latest rules_java 8.1.0
* Add loads for Java rules
NOTE: The loads and rules_java version unforutunately are tightly related. The paths for the bzl files for Java rules changed between rules_java 7 and 8.
=> Upgrade rules_java and add rule loads

MODULE.bazel, repositories.bzl
Also update rules_java to 7.12.2. It was accidentally left out in https://github.com/bazel-contrib/rules_jvm_external/pull/1273. 
With the rules_java bump for Bazel 6, it brings in additional dependencies on rules_cc and protobuf. cc @comius 
cc @ted-xie @ahumesky
=> Prepare for v6.5

MODULE.bazel, private/rules/coursier.bzl, repositories.bzl, rules_shell_patch.diff
This is for compatibility with Bazel 8 which does not contain a native sh_binary rule.
=> Add rules_shell and add loads for sh_binary

private/rules/has_maven_deps.bzl, private/rules/maven_project_jar.bzl
Fixes https://github.com/bazel-contrib/rules_jvm_external/issues/1241
A detailed description of the issue, minimal repo, and explanation of the fix can be found at https://github.com/vinnybod/bazel_java_example/tree/javadocs-srcs-issue?tab=readme-ov-file#solution
=> Fix docs generation for artifacts with compile only dependencies

private/extensions/maven.bzl
Fix feedback about noisy logs from https://github.com/bazelbuild/bazel-worker-api/issues/7#issue-2716146027
What was previously:
```
(15:01:37) DEBUG: /private/var/tmp/_bazel_blee/499a001013731d09bffd82f8601a3161/external/rules_jvm_external+/private/extensions/maven.bzl:155:14: The maven repository 'maven' is used in two different bazel modules, originally in 'protobuf' and now in 'bazel_worker_java'
(15:01:37) DEBUG: /private/var/tmp/_bazel_blee/499a001013731d09bffd82f8601a3161/external/rules_jvm_external+/private/extensions/maven.bzl:155:14: The maven repository 'maven' is used in two different bazel modules, originally in 'protobuf' and now in 'bazel_worker_java'
(15:01:37) DEBUG: /private/var/tmp/_bazel_blee/499a001013731d09bffd82f8601a3161/external/rules_jvm_external+/private/extensio …
```
=> Make multiple modules contributing to the same maven repo namespace warning less verbose and duplicated

private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/remote/HttpDownloader.java
With this change the following netrc would get the username set, it used to set an **empty username**:
```
machine artifacts.example.org
login bob
password superSecretPa$$word
```
=> [auth][netrc] Empty account fallback to login

.bazelci/presubmit.yml, private/lib/coordinates.bzl, private/rules/has_maven_deps.bzl, private/rules/java_export.bzl, private/rules/maven_bom.bzl, private/rules/maven_utils.bzl, private/rules/pom_file.bzl, tests/unit/runtime_scope/BUILD, tests/unit/runtime_scope/runtime_scope_test.bzl
A transitive dependency of a `maven_project_jar` is a runtime dependency if and only if each path to it from the root goes through at least one `runtime_deps` edge. Before this commit, every transitive dependency that was reachable from the root via at least one path with a `runtime_deps` edge was considered to be a runtime dependency, even if other paths require it as a compile dependency. This fixes a regression introduced by https://github.com/bazel-contrib/rules_jvm_external/commit/7b0abdc591b9b0b0dbdfd62bf9d98928b0efe6a2.
Also show a helpful error when users attempt to move a dep from `runtime_deps` to `deps` on a `java_export` target with no `srcs`.
Work towards https://github.com/CodeIntelligenceTesting/jazzer/issues/919
=> Fix collection of Maven runtime deps

private/artifact_utilities.bzl
When using `RJE_VERBOSE=1`, the resolution fails when logging this message because it was expecting two parameters in `.format`
=> Fix a fatal error when printing verbose logs when depedencies contain exclusions

README.md, private/rules/coursier.bzl, private/rules/pin_dependencies.bzl
Addresses https://github.com/bazel-contrib/rules_jvm_external/issues/445 and  https://github.com/bazel-contrib/rules_jvm_external/issues/1046 by taking the workaround in https://github.com/bazel-contrib/rules_jvm_external/issues/445 and applying it as the default before looking at JAVA_HOME.
I also added a way to give the JVM settings for both coursier and maven if a custom cacerts file was needed.  This can be set by doing
```
build --repo_env=JDK_JAVA_OPTIONS=-Djavax.net.ssl.trustStore=<path-to-cacerts>
```
in `.bazelrc` 
Based on [JDK_JAVA_OPTIONS](https://docs.oracle.com/en/java/javase/11/tools/java.html#GUID-3B1CE181-CD30-4178-9602-230B800D4FAE__USINGTHEJDK_JAVA_OPTIONSLAUNCHERENV-F3C0E3BA)
=> Use Bazel's JDK to run coursier

private/rules/coursier.bzl
Addresses https://github.com/bazel-contrib/rules_jvm_external/issues/1328/.
I am unaware of what additional implications this might have so pinging the authors of the original [maven resolver bom PR](https://github.com/bazel-contrib/rules_jvm_external/commit/3ec0bbb95278bf01f4d3e19b6c193d61e79ffc19) @shs96c @tirsen @cheister and of the [coursier resolver bom PR](https://github.com/bazel-contrib/rules_jvm_external/commit/3289580bcb40ae4e90d3ac8d1768405a7c78e22a) @protocol7 for review.
=> Pass boms during (unpinned) coursier fetch

README.md, private/extensions/maven.bzl
Small documentation update to explain in bzlmod one should use maven.override instead of override_targets
=> Add documentation for maven.override when using bzlmod

.bazelci/presubmit.yml
We've had several cases where we've needed to land additional PRs to fix things once they'd landed because we weren't building the entire repo.
We don't need to do this for our entire matrix of versions and OSs, but doing this in one place would be Really Nice.
=> [ci] At least one presubmit task should attempt to build everything

MODULE.bazel, private/extensions/maven.bzl
And only do this for repos that are declared in the root module, as we don't want to worry about repos that are not in the root module.
=> Indicate which `install` tag has duplicate coordinates

private/rules/coursier.bzl
We've run into some cases where `coursier fetch` will trigger an OutOfMemoryError and spin 100% of CPU doing useless garbage collection cycles on a very large input tree and where the amount of memory on the system running the pin command is not large enough, where the JVM is by default setting the max heap size to 25% of system memory.
This is easy enough to address by setting `COURSIER_OPTS`, but another thing we noticed along the way is that there is no trace of this OOM at all unless `RJE_VERBOSE` is set, since otherwise `--quiet` is passed to coursier. And since coursier isn't exiting on OOM, anyone running into this problem is stuck waiting for the `resolve_timeout` passed to `maven.install()`.
This patch adds the `-XX:ExitOnOutOfMemoryError` flag to `coursier_opts`, setting it …
=> set -XX:+ExitOnOutOfMemoryError when invoking coursier

private/rules/coursier.bzl, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/BUILD.bazel, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/GradleModuleMetadataHelper.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/GradleResolverTest.java, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/fixtures/BUILD.bazel, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/fixtures/jvmAndAndroidVariants/sample-1.0.module, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/fixtures/jvmAndAndroidVariants/sample-android-1.0.module, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/fixtures/jvmAndAndroidVariants/sample-jvm-1.0.module, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/fixtures/simpleJvmVariant/sample-1.0.module, tests/com/github/bazelbuild/rules_jvm_external/resolver/gradle/fixtures/simpleJvmVariant/sample-jvm-1.0.module
This adds additional unit tests for the gradle resolver. Currently we have all the test cases that are also shared with the maven resolver which is good but it's missing test cases specific to scenarios related to the gradle resolver. Specifically these test cases are needed because:
1. They can be used to verify that gradle module metadata is successfully resolved by the resolver and helps improve coverage and correctness of the resolver.
2. Gradle supports an arbitrary number of variants and consumers can choose what they want but right now, we really only support the default/JVM variant for the most cases. As we want to add support for more variants, having logic that helps us verify the correctness of resolution for multiple variants will be needed and quite helpful.
3. Integration …
=> Add more unit tests for gradle resolver
