- BUILD
- GMavenToBazel.java
- defs.bzl
- examples/AndroidManifest.xml
- settings.xml
> Add license headers to files

- README.md
> Add support policy and update README

- README.md
- WORKSPACE
- defs.bzl
- examples/BUILD
- examples/android_instrumentation_test/WORKSPACE
- examples/android_instrumentation_test/src/test/java/com/example/bazel/BUILD
- examples/simple/BUILD
- examples/simple/WORKSPACE
- tests/integration/BUILD
TODO: Rename this repository in lockstep while merging this PR.
> Rename gmaven_rules to rules_jvm_external

- .bazelci/presubmit.yml
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/34
> Add Buildkite configuration for new targets

- .bazelci/presubmit.yml
https://github.com/bazelbuild/rules_jvm_external/issues/53
https://github.com/bazelbuild/rules_jvm_external/issues/54
> Disable macOS and Windows integration build targets

- README.md
- WORKSPACE
https://mvnrepository.com/repos
> Correct the URL to the jcenter repository

- README.md
- docs/README.md
- docs/api.md
- specs.bzl
These are generated with the Stardoc integration in https://github.com/bazelbuild/rules_jvm_external/pull/66/
#66 is put on hold while we iron out https://github.com/bazelbuild/skydoc/issues/174
> Add API reference doc

- scripts/migrate_from_gmaven.sh
From https://github.com/jin/rules_maven/pull/14, adapted for `rules_jvm_external`'s 1.0 release.
> Create a migration script from gmaven_rules

- .bazelci/examples.yml
Tracking in https://github.com/bazelbuild/rules_jvm_external/issues/103
> Disable Scala example tests on Windows

- examples/spring_boot/LICENSE.code.txt
From https://github.com/spring-guides/gs-spring-boot/blob/d0f3a942f1b31ee73d2896c1e201f11cd8efd6ba/LICENSE.code.txt
> Add license to Spring Boot example

- WORKSPACE
- coursier.bzl
- tests/unit/build_tests/BUILD
Fixes #111 
Also added a regression test.
>  In generate_imports, correctly determine artifacts that already have a corresponding BUILD target

- WORKSPACE
- coursier.bzl
- tests/unit/build_tests/BUILD
> Support orbit package types

- WORKSPACE
- coursier.bzl
- tests/integration/BUILD
- tests/unit/build_tests/BUILD
See https://github.com/bazelbuild/rules_jvm_external/issues/119#issuecomment-484278260
> Add support for test-jar packaging type

- coursier.bzl
Coursier [supports](https://get-coursier.io/docs/1.1.0-M10/cli-fetch.html#multiple-classifiers) fetching the standard and source jars simultaneously, so use that instead of doing fetch two separate times.
> Fetch standard jars and sources at the same time

- README.md
Break fetch_sources and fail_on_missing_checksum attributes out into their own
sections.
> Update README to simplify initial WORKSPACE snippet

- .bazelci/presubmit.yml
- WORKSPACE
- coursier.bzl
- defs.bzl
- examples/android_instrumentation_test/WORKSPACE
- examples/android_kotlin_app/BUILD
- examples/android_kotlin_app/WORKSPACE
- examples/android_kotlin_app/src/BUILD
- examples/android_local_test/WORKSPACE
- examples/android_local_test/src/main/BUILD
- examples/pom_file_generation/BUILD
- examples/scala_akka/BUILD.bazel
- examples/scala_akka/WORKSPACE
- examples/simple/WORKSPACE
- examples/spring_boot/WORKSPACE
- examples/spring_boot/src/main/java/hello/BUILD.bazel
- examples/spring_boot/src/test/java/hello/BUILD.bazel
- private/jvm_import.bzl
- specs.bzl
- tests/integration/BUILD
- tests/unit/kotlin/BUILD
- tests/unit/specs_test.bzl
https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#legacy-format
> Buildifier and CI config cleanup

- .bazelci/presubmit.yml
- WORKSPACE
- tests/integration/ArtifactExclusionsTest.java
- tests/integration/BUILD
- tests/integration/NeverlinkTest.java
Work towards https://github.com/bazelbuild/rules_jvm_external/issues/128
> Fix some tests to be compatible with OpenJDK 11

- .bazelci/examples.yml
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/161
> Fix bad bazelci config

- WORKSPACE
- coursier.bzl
- tests/unit/build_tests/BUILD
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/172
> Fix cyclic dependencies by not generating dependencies that depend on itself

- coursier.bzl
See https://github.com/bazelbuild/rules_jvm_external/pull/169#discussion_r298530053
> Remove useless repository_ctx.execute call

- README.md
> Exporting Artifacts Docs

- README.md
..and reorder it to make it more prominent.
> Expand artifact pinning documentation

- coursier.bzl
- defs.bzl
- private/pin.sh
Fix https://github.com/bazelbuild/rules_jvm_external/issues/232
> Refactor pin.sh instructions

- .bazelci/examples.yml
- examples/pom_file_generation/WORKSPACE
Turns out this example was never tested on CI. Test it.
> Add CI for pom_file_example

- coursier.bzl
> Refactor coursier.bzl: reduce nesting level of a for loop body by inverting a conditional

- README.md
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/276
> Bump version to 2.9

- private/tools/BUILD
- private/tools/java/rules/jvm/external/Hasher.java
- private/tools/java/rules/jvm/external/HasherTest.java
I figured that we forgot to add tests in this PR #296, correctness of the hasher is quite important 😬
> Add tests for sha256 Hasher

- private/proxy.bzl
- tests/unit/proxy_test.bzl
Fix for https://github.com/bazelbuild/rules_jvm_external/issues/321
> Fix proxy port trailing slash

- examples/protobuf-java/WORKSPACE
- examples/protobuf-java/src/main/BUILD
> Use rules_proto for compatibility with --incompatible_load_proto_rules_from_bzl

- examples/scala_akka/WORKSPACE
rules_scala got hit by the HTTP Maven Central turndown.
> Fix failing scala examples builds

- WORKSPACE
- examples/android_kotlin_app/WORKSPACE
- examples/android_local_test/WORKSPACE
- examples/simple/WORKSPACE
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/364
> Pin Android SDK version to 28.0.2

- examples/android_instrumentation_test/.bazelrc
- examples/android_instrumentation_test/BUILD.bazel
To match configuration in https://github.com/android/testing-samples/commit/d8b814bed50d0fe29160f8fe830bd8bafda09dae
> Update RBE configuration

- README.md
- coursier.bzl
- defs.bzl
> support additional netrc lines for downloading pinned artifacts

- BUILD
- docs/api.md
- private/rules/BUILD
- private/rules/jvm_import.bzl
- settings/BUILD
> Generate new docs and fix docgen pipeline

- private/rules/has_maven_deps.bzl
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/430
> Fix compatibility with --incompatible_disable_depset_items

- defs.bzl
Refs: https://github.com/bazelbuild/rules_jvm_external/pull/439
> Export the MavenPublishInfo

- .bazelci/examples.yml
Doesn't work on Windows: https://github.com/bazelbuild/rules_jvm_external/issues/324
> Add pinning step to the simple example for user journey coverage

- private/tools/java/rules/jvm/external/javadoc/JavadocJarMaker.java
- private/tools/java/rules/jvm/external/javadoc/Version.java
- tests/com/jvm/external/javadoc/BUILD.bazel
- tests/com/jvm/external/javadoc/VersionTest.java
> Only generate frames for versions of Java < 13

- README.md
> Update README to reference 4.0

- .bazelci/presubmit.yml
- private/tools/java/rules/jvm/external/maven/Outdated.java
- tests/com/jvm/external/maven/BUILD
- tests/com/jvm/external/maven/OutdatedTest.java
Add tests for outdated class.
Follow on to https://github.com/bazelbuild/rules_jvm_external/pull/508 so we can test fixes for the outdated function
> Add tests for Outdated

- coursier.bzl
Often when I use RJE_VERBOSE I want to see the actual commands getting executed.  
This PR adds a wrapper method around repository_ctx.execute to output the command getting run before running the command when RJE_VERBOSE is true.
> Output actual command line when using RJE_VERBOSE

- examples/android_instrumentation_test/WORKSPACE
- examples/android_kotlin_app/WORKSPACE
- examples/android_local_test/WORKSPACE
- examples/simple/WORKSPACE
PRs are currently red as a result of this.
> Update Android build_tools_version and api_level in examples

- BUILD
- docs/api.md
> Update API docs

- repositories.bzl
I was doing something else and noticed this.
> remove unused load

- CODEOWNERS
https://github.com/bazelbuild/rules_jvm_external/issues/691
> Update CODEOWNERS for rules_jvm_external

- private/rules/java_export.bzl
Fixes https://github.com/bazelbuild/rules_jvm_external/issues/707.
> Set visibility in all `java_export` targets

- examples/android_local_test/WORKSPACE
- examples/android_local_test/maven_install.json
- examples/kt_android_local_test/WORKSPACE
- examples/kt_android_local_test/maven_install.json
See https://github.com/robolectric/robolectric-bazel/releases/tag/4.8.2.
> Bump Robolectric to 4.8.2

- examples/android_instrumentation_test/BUILD
- examples/android_instrumentation_test/WORKSPACE
use constraint values from @platforms and migrate to rbe_preconfig 
https://github.com/bazelbuild/continuous-integration/issues/1404
> use constraint values from @platforms and migrate to rbe_preconfig

- private/rules/maven_project_jar.bzl
`java_export` silently ignores `java_binary` targets in `deploy_env` since their `JavaInfo` has an empty runtime classpath. Since this is the direct opposite of how the attribute of the same name on `java_binary` works, which only accepts `java_binary` targets, this is quite error-prone and warrants a strong warning/failure.
Follow up to https://github.com/bazelbuild/rules_jvm_external/pull/776
> Fail on `java_binary` in `deploy_env` of `java_export`

- README.md
- coursier.bzl
- private/rules/maven_install.bzl
- specs.bzl
- tests/unit/specs_test.bzl
This is revisitation of https://github.com/bazelbuild/rules_jvm_external/pull/484.
> feature: add coursier --credentials from home netrc

- BUILD
- coursier.bzl
- private/dependency_tree_parser.bzl
- private/rules/BUILD
- private/rules/v1_lock_file.bzl
This starts laying the groundwork for us to replace the lock file format with something else without needing to rewrite everything from scratch.
> Provide an abstraction over the lock file format

- MODULE.bazel
I'll update this PR as we get closer to shipping with any changes we need, but I don't think there will be many.
> Prepare for releasing 5.2

- private/rules/java_export.bzl
excluded_workspaces is a dict not a list.
> Fix fallback type

- private/dependency_tree_parser.bzl
- tests/unit/jvm_import/jvm_import_test.bzl
This may help folks to do things like generate sbom files by looking at the attributes of jvm_import targets.
> Add explicit tag for repository used

- examples/bzlmod/MODULE.bazel
- private/rules/maven_bom_fragment.bzl
- private/tools/java/com/github/bazelbuild/rules_jvm_external/maven/MavenPublisher.java
- tests/unit/kotlin/BUILD
Just cleaning up formatting and deprecated imports.
> format files with bazel run //scripts:format

- coursier.bzl
Add `@maven//:pin` (an alias to `@unpinned_maven//:pin`) for convenience.
Note that this relies strongly on @maven existing, so `fail_if_repin_required` should be honored at all times (and therefore this PR maybe depends on https://github.com/bazelbuild/rules_jvm_external/pull/996)
> feat: Add @name//:pin target to pinned repository for convenience

- MODULE.bazel
- examples/android_kotlin_app/WORKSPACE
- examples/bzlmod/MODULE.bazel
- private/rules/java_export.bzl
- private/tools/java/com/github/bazelbuild/rules_jvm_external/javadoc/JavadocJarMaker.java
- scripts/BUILD
- tests/com/github/bazelbuild/rules_jvm_external/manifest/Print.java
> Fix format script

- private/rules/maven_publish.bzl
This is an attempt to address #936
> Add the ability to pass args to MavenPublisher

- private/rules/jvm_import.bzl
These PRs aren't needed since the downstream Bazel build just needed to pass `--tool_java_runtime_version` on top of
`--tool_java_language_version`.
cc @fmeum
> Revert #1058 and #1059

- .bazelci/examples.yml
https://github.com/bazelbuild/rules_jvm_external/issues/1067
> Temporarily turn down android_local_test examples builds on macOS

- MODULE.bazel
> Remove dev_dependency from rules_android in bzlmod

- private/extensions/maven.bzl
> Support use_credentials_from_home_netrc_file via bzlmod extension

- rules_jvm_external_deps_install.json
- tests/custom_maven_install/m2local_testing_ignore_empty_files_with_pinned_file_install.json
- tests/custom_maven_install/m2local_testing_with_pinned_file_install.json
Regenerated lock files after https://github.com/bazelbuild/rules_jvm_external/pull/1063 was merged
> Re-pin lock files so they have the new services element

- .gitignore
- tests/integration/plugin_targets/ClassUsingAnnotationProcessor.java
- tests/integration/plugin_targets/ClassUsingClassUsingAnnotationProcessor.java
And pick some format changes from running `bazel run //scripts:format`
> Add MODULE.bazel.lock to .gitignore until it is stable

- maven_install.json
- private/rules/v2_lock_file.bzl
- rules_jvm_external_deps_install.json
- tests/custom_maven_install/artifact_with_plus_repin_install.json
- tests/custom_maven_install/java_export_exclusion_testing_install.json
- tests/custom_maven_install/json_artifacts_testing_install.json
- tests/custom_maven_install/m2local_testing_ignore_empty_files_with_pinned_file_install.json
- tests/custom_maven_install/m2local_testing_with_pinned_file_install.json
- tests/custom_maven_install/manifest_stamp_testing_install.json
- tests/custom_maven_install/maven_install.json
- tests/custom_maven_install/multiple_lock_files_install.json
- tests/custom_maven_install/override_target_in_deps_install.json
- tests/custom_maven_install/policy_pinned_testing_install.json
- tests/custom_maven_install/regression_testing_coursier_install.json
- tests/custom_maven_install/service_indexing_testing.json
Since the maven resolver will generate lock files with sorted keys I think we should do the same for the coursier lock files.
> Sort lock-file keys

- private/rules/coursier.bzl
This pull request backports support for .netrc on Windows from [tools/build_defs/repo/utils.bzl#read_user_netrc](https://github.com/bazelbuild/bazel/blob/eb905bde4920954aefee0f018488d054cceaa772/tools/build_defs/repo/utils.bzl#L405) (#940).
> Add support for .netrc on Windows

- private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java
- tests/com/github/bazelbuild/rules_jvm_external/resolver/BUILD
- tests/com/github/bazelbuild/rules_jvm_external/resolver/MavenRepo.java
- tests/com/github/bazelbuild/rules_jvm_external/resolver/maven/BUILD
- tests/com/github/bazelbuild/rules_jvm_external/resolver/maven/ConsoleRepositoryListenerTest.java
- tests/com/github/bazelbuild/rules_jvm_external/resolver/maven/DownloaderTest.java
- tests/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolverTest.java
Follow up to https://github.com/bazelbuild/rules_jvm_external/pull/1156 to add unit tests
> Add unit tests for ConsoleRepositoryListener and Downloader

- private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/ResolutionRequest.java
- private/tools/java/com/github/bazelbuild/rules_jvm_external/resolver/maven/MavenResolver.java
- tests/com/github/bazelbuild/rules_jvm_external/resolver/ResolverTestBase.java
Follow-up to https://github.com/bazelbuild/rules_jvm_external/pull/1155 to add a test.
> Keep BOM's dependencies ordered in the same way they are declared

- MODULE.bazel
#1226 handles updating `rules_java`
> Prepare for 6.3 release by updating deps

- MODULE.bazel
- repositories.bzl
> Prepare for rules_jvm_external 6.4

- docs/BUILD
- private/lib/coordinates.bzl
- private/rules/maven_bom.bzl
- private/rules/maven_utils.bzl
- private/rules/v2_lock_file.bzl
- specs.bzl
- tests/unit/BUILD
- tests/unit/coordinates_test.bzl
- tests/unit/coursier_utilities_test.bzl
- tests/unit/specs_test.bzl
This PR should be landed as a "rebase and merge" rather than a "squash" commit.
> Normalise coordinate names

- examples/android_local_test/WORKSPACE
- examples/kt_android_local_test/WORKSPACE
> Bump robolectric-bazel to 4.14.1.2

- private/extensions/maven.bzl
In some cases it is valid for Bzlmod modules to inject additional dependencies into the default "maven" repository. In such cases the warning is not helpful and it should be possible to suppress it.
> [bzlmod] Allow suppressing warning about multiple contributing modules.

- docs/api.md
- private/rules/maven_install.bzl
Small update to the macro's docstring and update the generated docs using `scripts/generate_api_docs.sh` after adding the gradle resolver.
> Update docs for maven_install
